- type: entity
  name: spear
  parent: [BaseItem, SolutionDart, BaseMinorContraband]
  id: NivalisBaseSpear
  description: Definition of a Classic. Keeping murder affordable since 200,000 BCE.
  components:
  - type: Tool
    qualities:
    - Slicing
  - type: EmbeddableProjectile
    offset: -0.15,0.0
  - type: ThrowingAngle
    angle: 225
  - type: LandAtCursor
  - type: Tag
    tags:
    - Spear
    - ScurretWearable
  - type: Fixtures
    fixtures:
      fix1:
        shape: !type:PolygonShape
          vertices:
            - -0.40,-0.30
            - -0.30,-0.40
            - 0.40,0.30
            - 0.30,0.40
        density: 20
        mask:
        - ItemMask
        restitution: 0.3
        friction: 0.2
  - type: Sprite
    sprite: Objects/Weapons/Melee/spear.rsi
    layers:
    - state: spear
    - state: spear1
      map: ["enum.SolutionContainerLayers.Fill"]
      visible: false
  - type: NivalisMelee
    wideAnimationRotation: -135
    lightComboCount: 3
    lightComboInterval: 0.13
    lightComboRecovery: 0.5
    lightDamage:
      types: { Melee: 7 }
    lightStaminaDamage: 4
    heavyDamage:
      types: { Melee: 16 }
    heavyStaminaDamage: 8
    angle: 0
    range: 1.5
    animation: WeaponArcThrust
    wideAnimation: WeaponArcThrust
    soundHit:
      path: /Audio/Weapons/bladeslice.ogg
  - type: NivalisMeleeParry
    parryCooldown: 1.0
    parryWindow: 1.0
    failedParryPenalty: 0.5
    stunDuration: 1.5
  - type: Item
    size: Ginormous
    shape:
    - 0,0,0,6
    storedRotation: -45
  - type: Clothing
    quickEquip: false
    slots:
    - back
    - suitStorage
  - type: Construction
    graph: Spear
    node: spear
  - type: MeleeChemicalInjector
    solution: melee
  - type: RefillableSolution
    solution: melee
  - type: InjectableSolution
    solution: melee
  - type: SolutionInjectOnEmbed
    transferAmount: 2
    solution: melee
  - type: SolutionTransfer
    maxTransferAmount: 2
  - type: Damageable
  - type: Injurable
    damageContainer: Inorganic
  - type: Destructible
    thresholds:
    - trigger:
        !type:DamageTrigger
        damage: 20
      behaviors:
      - !type:PlaySoundBehavior
        sound:
          collection: GlassBreak
          params:
            volume: -4
      - !type:SpawnEntitiesBehavior
        spawn:
          PartRodMetal1:
            min: 1
            max: 1
      - !type:DoActsBehavior
        acts: [ "Destruction" ]
  - type: DamageOnLand
    damage:
      types:
        Blunt: 5
  - type: UseDelay
  - type: Appearance
  - type: SolutionContainerVisuals
    maxFillLevels: 1
    fillBaseName: spear
    inHandsFillBaseName: -fill-
    inHandsMaxFillLevels: 1
    equippedFillBaseName: -fill-
    equippedMaxFillLevels: 1