using System;
using System.Collections.Generic;
using System.Linq;
using System.Numerics;
using Content.Client.GameTicking.Managers;
using Content.Client.Lobby;
using Content.Client.Lobby.UI;
using Content.Client.Lobby.UI.ProfileEditorControls;
using Content.Client.Resources;
using Content.Client.UserInterface.Systems.Chat.Widgets;
using Content.Shared.Humanoid.Prototypes;
using Content.Shared.Preferences;
using Content.Shared._Nivalis.GameTicking;
using Content.Shared._Nivalis.Traits;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.IoC;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;
using SixLabors.ImageSharp.PixelFormats;

namespace Content.Client._Nivalis.UserInterface.Lobby;

[GenerateTypedNameReferences]
public sealed partial class NivalisLobbyControl : Control
{
    public event Action<string>? NavigationPressed;

    [Dependency] private IClientPreferencesManager _preferences = default!;
    [Dependency] private IEntityManager _entityManager = default!;
    [Dependency] private IClientConsoleHost _consoleHost = default!;
    [Dependency] private IEntityNetworkManager _netManager = default!;
    [Dependency] private IResourceCache _resourceCache = default!;
    [Dependency] private IUriOpener _uriOpener = default!;
    [Dependency] private IPrototypeManager _proto = default!;

    private readonly Dictionary<Button, ScrollingScanlineStyleBox> _navStyle = new();
    private readonly Dictionary<Button, Vector2> _navBaseSize = new();
    private readonly Dictionary<Button, Vector2> _navCurrentSize = new();
    private readonly Dictionary<Button, Vector2> _navTargetSize = new();
    private readonly Dictionary<Button, bool> _navHover = new();
    private readonly Dictionary<Button, float> _navHoverAmount = new();
    private readonly Dictionary<Button, int> _navIndex = new();

    private Button[] _navButtons = Array.Empty<Button>();

    private const int MaxTraits = 3;
    private readonly List<ProtoId<NivalisTraitPrototype>> _selectedTraits = new();
    private readonly Dictionary<Button, ProtoId<NivalisTraitPrototype>> _traitPickButtons = new();
    private bool _traitsPanelOpen;
    private bool _perksPanelOpen;
    private PerkInfo? _selectedPerk;
    private readonly List<Button> _perkBtns = new();
    private readonly Dictionary<Button, PerkInfo> _perkPickData = new();
    private readonly Dictionary<Button, ScrollingScanlineStyleBox> _perkStyle = new();
    private readonly Dictionary<Button, ScrollingScanlineStyleBox> _perkSelectedStyle = new();
    private Button? _hoveredPerkTile;
    private ScrollingScanlineStyleBox _perksInfoBox = new();
    private readonly Dictionary<Button, float> _perkEngaged = new();
    private float _perkInfoAnim;
    private bool _showPerkInfo;

    private const string PerkIconDir = "/Textures/_Nivalis/Interface/perkicons.rsi/";

    private sealed class PerkInfo
    {
        public string Icon = string.Empty;
        public string Name = string.Empty;
        public string Description = string.Empty;
        public List<string> Pros = new();
        public List<string> Cons = new();
    }

    public event Action? TraitsChanged;

    public IReadOnlyList<ProtoId<NivalisTraitPrototype>> SelectedTraits => _selectedTraits;

    private bool _areWeReady;
    private Texture? _scanlineTexture;

    private const float HoverScale = 1.08f;
    private const float HoverLerpSpeed = 9f;

    private const float IdleScrollSpeed = 9f;
    private const float HoverScrollSpeed = 26f;

    private const float NeighborShrinkScale = 0.96f;

    private Font _displayBold = null!;
    private Font _displayRegular = null!;
    private Font _displaySmall = null!;
    private Font _displayTiny = null!;
    public NivalisLobbyControl()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        _displayBold = _resourceCache.GetFont("/Fonts/Orbitron/Orbitron-Bold.ttf", 28);
        _displayRegular = _resourceCache.GetFont("/Fonts/Orbitron/Orbitron-Regular.ttf", 15);
        _displaySmall = _resourceCache.GetFont("/Fonts/Orbitron/Orbitron-Regular.ttf", 11);
        _displayTiny = _resourceCache.GetFont("/Fonts/Orbitron/Orbitron-Regular.ttf", 9);
        LayoutContainer.SetAnchorPreset(BackgroundViewport, LayoutContainer.LayoutPreset.Wide);
        LayoutContainer.SetAnchorAndMarginPreset(Header, LayoutContainer.LayoutPreset.TopWide, margin: 20);
        LayoutContainer.SetAnchorAndMarginPreset(ChatPanel, LayoutContainer.LayoutPreset.RightWide, margin: 18);
        LayoutContainer.SetAnchorAndMarginPreset(CharacterViewport, LayoutContainer.LayoutPreset.Center);
        LayoutContainer.SetAnchorAndMarginPreset(Navigation, LayoutContainer.LayoutPreset.CenterLeft, margin: 30);
        LayoutContainer.SetAnchorAndMarginPreset(ProgressionBox, LayoutContainer.LayoutPreset.BottomLeft, margin: 24);

        _scanlineTexture = GenerateScanlines();

        BackgroundViewport.Texture = null;

        TitleLabel.FontOverride = _displayBold;
        TitleLabel.Margin = new Thickness(0, 0, 0, 4);
        foreach (var label in HeaderLabels())
            label.FontOverride = _displayRegular;

        ReadyButton.OnPressed += OnReadyPressed;
        LoadoutButton.OnPressed += _ => NavigationPressed?.Invoke("loadout");
        TraitsButton.OnPressed += OnTraitsPressed;
        PerksButton.OnPressed += OnPerksPressed;
        ChallengesButton.OnPressed += _ => NavigationPressed?.Invoke("challenges");
        QuartermasterButton.OnPressed += _ => NavigationPressed?.Invoke("quartermaster");
        PatreonButton.OnPressed += _ => _uriOpener.OpenUri("https://www.patreon.com/cw/lynnite");
        SettingsButton.OnPressed += _ => NavigationPressed?.Invoke("settings");
        QuitButton.OnPressed += _ => _consoleHost.ExecuteCommand("disconnect");

        SetupNavButtons();
        BuildTraitsMenu();
        PositionTraitsPanel();
        BuildPerksMenu();
        ClearPerksInfo();
        PositionPerksPanel();

        TraitsChanged += OnTraitsChanged;
    }

    private void PositionTraitsPanel()
    {
        var parent = TraitsPanel.Parent;
        if (parent == null)
            return;

        TraitsPanel.PanelOverride = _traitsPanelBackground;

        UpdateCarouselEffects();

        var parentSize = parent.Size;
        if (parentSize.X <= 1 || parentSize.Y <= 1)
            return;

        TraitsPanel.Measure(parentSize);
        var height = Math.Clamp(TraitsPanel.DesiredSize.Y, TraitsPanel.MinHeight, TraitsPanel.MinHeight);
        if (height <= 0)
            height = 520;
        height = Math.Clamp(height, 0, parentSize.Y - 40);

        var traitsCenterY = TraitsButton.GlobalPosition.Y + TraitsButton.Height / 2f;
        var left = TraitsButton.GlobalPosition.X + TraitsButton.Width + 14;
        var top = traitsCenterY - height / 2f;

        var width = (parentSize.X - left - 14) / 2;
        width = Math.Max(width, TraitsPanel.MinWidth);

        left = Math.Clamp(left, 14, parentSize.X - width - 14);
        top = Math.Clamp(top, 14, parentSize.Y - height - 14);

        LayoutContainer.SetAnchorPreset(TraitsPanel, LayoutContainer.LayoutPreset.TopLeft);
        LayoutContainer.SetMarginLeft(TraitsPanel, left);
        LayoutContainer.SetMarginTop(TraitsPanel, top);
        LayoutContainer.SetMarginRight(TraitsPanel, left + width);
        LayoutContainer.SetMarginBottom(TraitsPanel, top + height);
    }

    private void OnTraitsChanged()
    {
        _netManager.SendSystemNetworkMessage(new NivalisTraitsSelectedMessage
        {
            Traits = new List<ProtoId<NivalisTraitPrototype>>(_selectedTraits),
        });
    }

    private IEnumerable<Label> HeaderLabels()
    {
        yield return ReadyCountValue;
        yield return ActiveCountValue;
        yield return RespawnTimerValue;
        yield return CycleValue;
        yield return LevelValue;
        yield return OdensValue;
        yield return BondsValue;
        yield return TierValue;
    }

    public void AttachChat(ChatBox chat)
    {
        chat.Orphan();
        ChatSlot.AddChild(chat);
        chat.Margin = new Thickness(2, 2, 2, 2);
        chat.MinSize = default;
        chat.HorizontalExpand = true;
        chat.VerticalExpand = true;

        chat.ChatWindowPanel.MinSize = default;
        chat.ChatWindowPanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = Color.FromHex("#1a2a3acc"),
            BorderColor = Color.FromHex("#0a162223"),
            BorderThickness = new Thickness(1, 1, 1, 1),
        };
    }
    public void HideDefaultLobby(LobbyGui lobby, ChatBox chat)
    {
        lobby.RightSide.Visible = false;
        AttachChat(chat);

        if (lobby.LobbySong.Parent is { } songParent)
            songParent.Visible = false;
    }

    private static Texture GenerateScanlines()
    {
        const int width = 64;
        const int height = 6;

        using var image = new SixLabors.ImageSharp.Image<Rgba32>(
            SixLabors.ImageSharp.Configuration.Default, width, height);
        for (var y = 0; y < height; y++)
        {
            var dark = (y == 1 || y == 3);
            byte r = 20, g = 40, b = 70, a = 0;
            if (dark)
            {
                a = 150;
                r = 30; g = 45; b = 90;
            }
            else if (y == 2)
            {
                a = 70;
                r = 160; g = 215; b = 255;
            }

            for (var x = 0; x < width; x++)
            {
                image[x, y] = new Rgba32(r, g, b, a);
            }
        }

        return Texture.LoadFromImage(image, "NivalisScanlines");
    }

    private void SetupNavButtons()
    {
        _navButtons = new[] { ReadyButton, LoadoutButton, TraitsButton, PerksButton, ChallengesButton, QuartermasterButton, PatreonButton, SettingsButton, QuitButton };
        for (var i = 0; i < _navButtons.Length; i++)
        {
            var button = _navButtons[i];
            button.Margin = new Thickness(i * 5, 0, 0, 4);
            button.HorizontalExpand = false;
            button.HorizontalAlignment = HAlignment.Left;

            var baseSize = new Vector2(button.MinWidth, button.MinHeight);
            _navBaseSize[button] = baseSize;
            _navCurrentSize[button] = baseSize;
            _navTargetSize[button] = baseSize;
            _navHover[button] = false;
            _navHoverAmount[button] = 0f;
            _navIndex[button] = i;

            var scanlineBox = new ScrollingScanlineStyleBox
            {
                Texture = _scanlineTexture,
                BackgroundColor = Color.FromHex("#A9D8FF").WithAlpha(0.38f),
                BorderColor = Color.FromHex("#D3EFFF").WithAlpha(0.5f),
                BorderThickness = 1f,
                InwardLean = 0.08f,
            };

            _navStyle[button] = scanlineBox;
            button.StyleBoxOverride = scanlineBox;

            button.OnMouseEntered += _ => OnNavHover(button, true);
            button.OnMouseExited += _ => OnNavHover(button, false);
        }
    }

    private void CloseTraitsPanel()
    {
        _traitsPanelOpen = false;
        TraitsPanel.Visible = false;
    }

    private void ClosePerksPanel()
    {
        _perksPanelOpen = false;
        PerksPanel.Visible = false;
    }

    private void OnTraitsPressed(BaseButton.ButtonEventArgs args)
    {
        if (_traitsPanelOpen)
        {
            CloseTraitsPanel();
            DimNavButtons(false);
            return;
        }

        ClosePerksPanel();
        _traitsPanelOpen = true;
        TraitsPanel.Visible = true;
        RebuildTraitMenu();
        PositionTraitsPanel();
        DimNavButtons(true);
    }

    private void OnPerksPressed(BaseButton.ButtonEventArgs args)
    {
        if (_perksPanelOpen)
        {
            ClosePerksPanel();
            DimNavButtons(false);
            return;
        }

        CloseTraitsPanel();
        _perksPanelOpen = true;
        PerksPanel.Visible = true;
        PositionPerksPanel();
        if (_selectedPerk == null)
        {
            ClearPerksInfo();
            PerksInfoPanel.Modulate = new Color(1f, 1f, 1f, 0f);
            _perkInfoAnim = 0f;
        }
        else
        {
            _showPerkInfo = true;
            _perkInfoAnim = 0f;
            PerksInfoPanel.Modulate = new Color(1f, 1f, 1f, 0f);
        }
        DimNavButtons(true);
    }

    private void RebuildTraitMenu()
    {
            BuildTraitsMenu();
    }

    private readonly StyleBoxFlat _traitSelectedBox = new()
    {
        BackgroundColor = Color.FromHex("#2a4a70cc"),
        BorderColor = Color.FromHex("#58C6E8"),
        BorderThickness = new Thickness(2, 2, 2, 2),
        ContentMarginTopOverride = 4,
        ContentMarginBottomOverride = 4,
        ContentMarginLeftOverride = 8,
        ContentMarginRightOverride = 8,
    };

    private readonly Dictionary<Button, ScrollingScanlineStyleBox> _traitStyle = new();

    private readonly StyleBoxFlat _traitsPanelBackground = new()
    {
        BackgroundColor = new Color(8, 11, 18, 200),
        ContentMarginLeftOverride = 6,
        ContentMarginRightOverride = 6,
        ContentMarginTopOverride = 6,
        ContentMarginBottomOverride = 6,
    };

    private readonly Dictionary<Button, int> _traitIndex = new();

    private void BuildTraitsMenu()
    {
        ArcContainer.RemoveAllChildren();
        _traitPickButtons.Clear();
        _traitStyle.Clear();
        _traitIndex.Clear();

        var traits = _proto.EnumeratePrototypes<NivalisTraitPrototype>().ToList();
        for (var i = 0; i < traits.Count; i++)
        {
            var trait = traits[i];
            var name = Loc.GetString(trait.Name);
            var desc = Loc.GetString(trait.Description);

            var pickButton = new Button
            {
                HorizontalAlignment = HAlignment.Right,
                MinSize = new Vector2(320, 70),
                MaxSize = new Vector2(320, 70),
            };

            var content = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                HorizontalExpand = true,
            };
            var header = new Label
            {
                Text = name,
                FontColorOverride = Color.FromHex("#CFE3FF"),
                HorizontalExpand = true,
                Margin = new Thickness(12, 5, 12, 1),
            };
            var descLabel = new Label
            {
                Text = desc,
                FontColorOverride = Color.FromHex("#8FA3B8"),
                FontOverride = _displayTiny,
                HorizontalExpand = true,
                Margin = new Thickness(12, 0, 12, 6),
            };
            content.AddChild(header);
            content.AddChild(descLabel);
            pickButton.AddChild(content);

            var traitId = new ProtoId<NivalisTraitPrototype>(trait.ID);
            pickButton.OnPressed += _ => OnTraitToggled(traitId);
            _traitPickButtons[pickButton] = traitId;
            _traitIndex[pickButton] = i;

            var scanlineBox = new ScrollingScanlineStyleBox
            {
                Texture = _scanlineTexture,
                InwardLean = -0.08f,
                FadeRight = 0.55f,
            };
            _traitStyle[pickButton] = scanlineBox;
            pickButton.StyleBoxOverride = scanlineBox;

            ArcContainer.AddChild(pickButton);
        }

        RefreshTraitHighlights();
        RefreshTraitsCount();
    }

    private void OnTraitToggled(ProtoId<NivalisTraitPrototype> traitId)
    {
        if (_selectedTraits.Contains(traitId))
        {
            _selectedTraits.Remove(traitId);
        }
        else if (_selectedTraits.Count < MaxTraits)
        {
            _selectedTraits.Add(traitId);
        }

        RefreshTraitHighlights();
        RefreshTraitsCount();
        TraitsChanged?.Invoke();
    }

    private void RefreshTraitHighlights()
    {
        foreach (var (button, traitId) in _traitPickButtons)
        {
            var selected = _selectedTraits.Contains(traitId);
            if (selected)
                button.StyleBoxOverride = _traitSelectedBox;
            else if (_traitStyle.TryGetValue(button, out var scanline))
                button.StyleBoxOverride = scanline;
        }
    }

    private void RefreshTraitsCount()
    {
        TraitsCountValue.Text = $"SELECTED: {_selectedTraits.Count}/{MaxTraits}";
    }

    private void UpdateCarouselEffects()
    {
        if (_traitPickButtons.Count == 0)
            return;

        var viewport = Math.Max(TraitsScroll.Size.Y, 1f);
        var scroll = TraitsScroll.VScroll;
        var baseH = 70f;
        var sep = 14f;
        var stride = baseH + sep;

        var available = Math.Max(TraitsScroll.Size.X - 16f, 1f);
        var halfSpan = Math.Max(viewport * 0.8f, 1f);

        var focusCenter = scroll + viewport / 2f;

        foreach (var (button, _) in _traitPickButtons)
        {
            var idx = _traitIndex[button];
            var rowCenter = idx * stride + baseH / 2f;
            var t = Math.Clamp(Math.Abs(rowCenter - focusCenter) / halfSpan, 0f, 1f);
            t = t * t * (3f - 2f * t);

            var bright = 1.12f - t * 0.45f;
            button.Modulate = new Color(bright, bright, bright, 1f);

            var height = baseH * (1f + 0.2f * (1f - t));
            var popUp = (1f - t) * 3f;

            var width = available * (1f - t * 0.18f);
            button.HorizontalAlignment = HAlignment.Right;
            button.MinSize = new Vector2(width, height);
            button.MaxSize = new Vector2(width, height);
            button.Margin = new Thickness(0, -popUp, 0, popUp);
        }
    }

    private void DimNavButtons(bool dimmed)
    {
        var dim = dimmed ? Color.FromHex("#33333a") : Color.White;
        var active = _traitsPanelOpen ? TraitsButton : _perksPanelOpen ? PerksButton : null;

        foreach (var button in _navStyle.Keys)
        {
            if (ReferenceEquals(button, active))
                continue;

            _navStyle[button].Modulate = dimmed ? dim : Color.White;
        }
    }

    private void OnNavHover(Button button, bool hovering)
    {
        _navHover[button] = hovering;
    }

    private void UpdateNavAnimations(float frameTime)
    {
        var hoveredIndex = -1;
        foreach (var kvp in _navHover)
        {
            if (kvp.Value)
            {
                hoveredIndex = _navIndex[kvp.Key];
                break;
            }
        }

        foreach (var button in _navButtons)
        {
            var baseSize = _navBaseSize[button];
            var idx = _navIndex[button];
            var isHovered = idx == hoveredIndex;
            var isNeighbor = hoveredIndex >= 0 && Math.Abs(idx - hoveredIndex) == 1;

            if (isHovered)
            {
                _navTargetSize[button] = new Vector2(baseSize.X * HoverScale, baseSize.Y * HoverScale);
            }
            else if (isNeighbor)
            {
                _navTargetSize[button] = new Vector2(baseSize.X, baseSize.Y * NeighborShrinkScale);
            }
            else
            {
                _navTargetSize[button] = baseSize;
            }
        }

        foreach (var (button, style) in _navStyle)
        {
            var current = _navCurrentSize[button];
            var target = _navTargetSize[button];
            var hoverAmount = _navHoverAmount[button];

            var amountTarget = _navHover[button] ? 1f : 0f;
            var lerp = 1f - MathF.Exp(-HoverLerpSpeed * frameTime);
            var amount = hoverAmount + (amountTarget - hoverAmount) * lerp;
            _navHoverAmount[button] = amount;

            var newSize = new Vector2(
                current.X + (target.X - current.X) * lerp,
                current.Y + (target.Y - current.Y) * lerp);
            _navCurrentSize[button] = newSize;
            button.MinSize = newSize;

            var speed = _navHover[button] ? HoverScrollSpeed : IdleScrollSpeed;
            style.ScrollOffset += frameTime * speed;

            var bright = 0.82f + 0.15f * amount;
            style.Modulate = new Color(bright, bright, bright, 1f);
        }

        foreach (var style in _traitStyle.Values)
        {
            style.ScrollOffset += frameTime * IdleScrollSpeed;
        }

        foreach (var style in _perkStyle.Values)
        {
            style.ScrollOffset += frameTime * IdleScrollSpeed;
        }

        if (_traitsPanelOpen)
        {
            PositionTraitsPanel();
            DimNavButtons(true);
        }
        else if (_perksPanelOpen)
        {
            _perksInfoBox.ScrollOffset += frameTime * IdleScrollSpeed;
            UpdatePerksHoverHighlight(frameTime);
            PositionPerksPanel();
            DimNavButtons(true);
        }
    }

    private void OnReadyPressed(BaseButton.ButtonEventArgs args)
    {
        var ticker = _entityManager.System<ClientGameTicker>();
        if (ticker.IsGameStarted)
        {
            _netManager.SendSystemNetworkMessage(new NivalisJoinGameMessage());
            return;
        }

        var newState = !ticker.AreWeReady;
        _consoleHost.ExecuteCommand($"toggleready {newState}");
        SetReadyState(newState);
    }

    public void SetReadyState(bool ready)
    {
        _areWeReady = ready;
        var ticker = _entityManager.System<ClientGameTicker>();
        ReadyButton.Text = ticker.IsGameStarted
            ? "JOIN GAME"
            : ready ? "READY" : "NOT READY";
    }

    public void LoadCharacterPreview()
    {
        // Can't spawn the character dummy until the entity manager is fully initialised
        // (its MetaQuery/entity store is only set up during EntityManager.Initialize).
        // The LobbyUIController reloads the preview whenever the LobbyState is entered,
        // so it's safe to defer if preferences arrive before we're ready.
        if (_entityManager is EntityManager { Initialized: false })
            return;

        if (_preferences.Preferences?.SelectedCharacter is not HumanoidCharacterProfile humanoid)
        {
            AgentPreview.ClearPreview();
            AgentNameLabel.Text = "UNKNOWN";
            return;
        }

        // The character preview can't spawn a humanoid for a species that lacks a doll
        // prototype, which would otherwise throw at runtime. Fall back to the default
        // species in that case so the lobby always has a working preview.
        if (!_proto.HasIndex<SpeciesPrototype>(humanoid.Species)
            || _proto.Index<SpeciesPrototype>(humanoid.Species).DollPrototype == default)
        {
            humanoid = new HumanoidCharacterProfile(humanoid)
            {
                Species = HumanoidCharacterProfile.DefaultSpecies,
            };
        }

        AgentPreview.LoadPreview(humanoid);
        AgentNameLabel.Text = humanoid.Name;

        if (AgentTitleLabel.FontOverride == null)
            AgentTitleLabel.FontOverride = _displayRegular;
        AgentNameLabel.FontOverride = _displayRegular;
    }

    public void UpdatePlayerProgression(int level, int odens, int bonds, int tier)
    {
        LevelValue.Text = level.ToString();
        OdensValue.Text = odens.ToString();
        BondsValue.Text = bonds.ToString();
        TierValue.Text = tier.ToString();
    }

    public void UpdateMatchStats(int readyCount, int activeCount, TimeSpan respawnRemaining, int cycle)
    {
        ReadyCountValue.Text = readyCount.ToString();
        ActiveCountValue.Text = activeCount.ToString();

        RespawnTimerValue.Text = respawnRemaining <= TimeSpan.Zero
            ? "0:00"
            : $"{(int) Math.Ceiling(respawnRemaining.TotalSeconds) / 60}:{(int) Math.Ceiling(respawnRemaining.TotalSeconds) % 60:00}";

        CycleValue.Text = cycle.ToString();
    }

    public void UpdateDiagnostics(float frameTime)
    {
        var ticker = _entityManager.System<ClientGameTicker>();
        if (ticker.AreWeReady != _areWeReady)
            SetReadyState(ticker.AreWeReady);
        else if (ticker.IsGameStarted && ReadyButton.Text != "JOIN GAME")
            SetReadyState(_areWeReady);

        UpdateNavAnimations(frameTime);
    }

    private void PositionPerksPanel()
    {
        var parent = PerksPanel.Parent;
        if (parent == null)
            return;

        PerksPanel.PanelOverride = _traitsPanelBackground;

        var parentSize = parent.Size;
        if (parentSize.X <= 2 || parentSize.Y <= 2)
        {
            parentSize = new Vector2(1280, 720);
        }

        PerksPanel.Measure(parentSize);
        var height = Math.Clamp(PerksPanel.DesiredSize.Y, PerksPanel.MinHeight, PerksPanel.MinHeight);
        if (height <= 0)
            height = 540;
        height = Math.Clamp(height, 0, parentSize.Y - 40);

        var perksY = PerksButton.GlobalPosition.Y + PerksButton.Height / 2f;
        var left = PerksButton.GlobalPosition.X + PerksButton.Width + 14;
        var top = perksY - height / 2f;

        var width = (parentSize.X - left - 14) / 2;
        width = Math.Max(width, PerksPanel.MinWidth);

        left = Math.Clamp(left, 14, parentSize.X - width - 14);
        top = Math.Clamp(top, 14, parentSize.Y - height - 14);

        LayoutContainer.SetAnchorPreset(PerksPanel, LayoutContainer.LayoutPreset.TopLeft);
        LayoutContainer.SetMarginLeft(PerksPanel, left);
        LayoutContainer.SetMarginTop(PerksPanel, top);
        LayoutContainer.SetMarginRight(PerksPanel, left + width);
        LayoutContainer.SetMarginBottom(PerksPanel, top + height);
    }

    private static List<(string Icon, string Name)> PerkSeeds()
    {
        return new()
        {
            ("survivalist", "Survivalist"),
            ("damned", "Damned"),
            ("lazarus", "Lazarus"),
            ("zealoth", "Zealot"),
            ("prophet", "Prophet"),
            ("sovereign", "Sovereign"),
            ("mindflawyer", "Mindflayer"),
            ("immolator", "Immolator"),
            ("vagabond", "Vagabond"),
            ("arbiter", "Arbiter"),
            ("executioner", "Executioner"),
            ("berserker", "Berserker"),
            ("artillerist", "Artillerist"),
            ("riskrunner", "Riskrunner"),
            ("hivemind", "Hivemind"),
            ("blitzer", "Blitzer"),
            ("tickspider", "Tickspider"),
            ("crosslink", "Crosslink"),
        };
    }

    private static string PerksFlavor(string name)
    {
        return name switch
        {
            "Survivalist" => "You've learned that the only way to survive alone is to be prepared for everything.",
            "Damned" => "Condemned and cursed, you've lost everything. The only way forward is to survive when all is lost.",
            "Lazarus" => "Through the art of experience, you believe that self perseverance is the strongest motivator to survival.",
            "Zealot" => "You believe that a strong bond is the true path to survival. Will and Dedication would only get you so far alone.",
            "Prophet" => "A keen eye for supplies and tactical planning is the only way for survival; you intend to capitalize on that.",
            "Sovereign" => "You believe in the truth of a higher power that will guide you not only to survival - but also true enlightenment.",
            "Mindflayer" => "You believe that intellect and wits are the only way to truly survive; without planning ahead, others are lost.",
            "Immolator" => "Cursing all as unclean, you firmly stand that the only way to survive is to light a torch to all that is unwelcome.",
            "Vagabond" => "There is only one constant to surviving alone: taking matters into your own hands, no matter the costs.",
            "Arbiter" => "You believe that taking initiative and setting things straight first is the only way for survival to succeed.",
            "Executioner" => "You believe you have a job to do, and surviving only comes second to accomplishing what is due.",
            "Berserker" => "Carving a path through relentless battles, you believe that survival is to overcome anything alone, no matter the odds.",
            "Artillerist" => "One shot, one kill - an art form you believe in, with every shot capable of opening opportunities.",
            "Riskrunner" => "You believe that overwhelming firepower is the only way to survive - to blaze through all odds.",
            "Hivemind" => "We believe in the safety of us, in safety in numbers; survival is only second nature to being collective as one.",
            "Blitzer" => "You believe in the brave and the risk takers who have survived through their commitment; you intend to be part of that list.",
            "Tickspider" => "Trickery and cunningness are what let you survive on your own terms without relying on others.",
            "Crosslink" => "An elegant dancer, from one wire to another on a razor-thin thread - you believe true finesse can carry you to the end.",
            _ => string.Empty,
        };
    }

    private static string[] PerkPros(string name)
    {
        return name switch
        {
            "Survivalist" => new[]
            {
                "Start with all inventory slots (Backpack).",
                "More resilient to hunger and thirst; ration buff applies above 75% bar, decay twice as slow.",
                "Extra home supplies (+50 scrap).",
                "Starts with rations (3 R.I Beans, 3 UlayCola, 1 M.R.E Lunchbox, 1 Aquafill Bottle).",
            },
            "Damned" => new[]
            {
                "Morale does not affect you.",
                "Fearless: Hanger influence immunity, can shove the Skinner, can parry the Sickler.",
            },
            "Lazarus" => new[]
            {
                "+20 max health.",
                "Immune to Bleeds.",
            },
            "Zealot" => new[]
            {
                "+35% damage resistance.",
                "+35 max health.",
            },
            "Prophet" => new[]
            {
                "+20% walkspeed.",
                "+50% faster harvesting.",
                "No fall damage.",
                "+50% faster crude crafting.",
            },
            "Sovereign" => new[]
            {
                "+50 stamina.",
                "Cursed Dagger: shoving applies Hex and deals 10 damage.",
            },
            "Mindflayer" => new[]
            {
                "+20% walkspeed.",
                "+25% shove speed.",
            },
            "Immolator" => new[]
            {
                "Immune to Burning.",
                "+25% melee damage.",
            },
            "Vagabond" => new[]
            {
                "+30% attack speed.",
                "+15% walkspeed.",
                "+15% melee damage.",
            },
            "Arbiter" => new[]
            {
                "+30% melee damage.",
                "Immune to Cripple.",
                "+30 max health.",
            },
            "Executioner" => new[]
            {
                "+20% damage resistance.",
                "+50 stamina.",
                "+30% attack speed.",
                "+25% shove speed.",
            },
            "Berserker" => new[]
            {
                "+25% melee damage.",
                "+15% damage resistance.",
                "Unable to be Grappled.",
                "Immune to Fracture.",
            },
            "Artillerist" => new[]
            {
                "+50% reload speed.",
                "+40% hipfire accuracy.",
                "Scavenge ~33% more ammo.",
            },
            "Riskrunner" => new[]
            {
                "+80% hipfire accuracy.",
                "+80% recoil control.",
                "Unable to be Grappled.",
            },
            "Hivemind" => new[]
            {
                "Immune to Bleed.",
                "HIVE Aura (area of insects that apply sickness to nearby enemies).",
            },
            "Blitzer" => new[]
            {
                "+65% aiming speed.",
                "+30% damage with Explosives.",
                "Immune to Explosive effects.",
            },
            "Tickspider" => new[]
            {
                "+30% damage with Explosives.",
                "+50% trap deployment speed.",
                "+40% recoil control.",
            },
            "Crosslink" => new[]
            {
                "+20% walkspeed.",
                "+30% hipfire accuracy.",
                "+50% trap deployment speed.",
                "Does not set off traps.",
            },
            _ => Array.Empty<string>(),
        };
    }

    private static string[] PerkCons(string name)
    {
        return name switch
        {
            "Survivalist" => Array.Empty<string>(),
            "Damned" => new[]
            {
                "Reduced combat and movement (-40% melee, shove, attack, walkspeed, defense; -55% recoil, reload, hipfire).",
                "Cannot aim with ranged weapons.",
                "Starving.",
                "No access to auxiliary equipment.",
                "Start without scrap.",
            },
            "Lazarus" => new[]
            {
                "Drop ranged weapons on damage.",
                "-25% reload speed.",
                "-20% melee damage.",
            },
            "Zealot" => new[]
            {
                "-15% walkspeed.",
                "-25% attack speed.",
            },
            "Prophet" => new[]
            {
                "-15% melee damage.",
            },
            "Sovereign" => new[]
            {
                "-15% melee damage.",
                "-10% walkspeed.",
            },
            "Mindflayer" => new[]
            {
                "-15% recoil control.",
                "-20% damage resistance.",
            },
            "Immolator" => new[]
            {
                "-15% reload speed.",
            },
            "Vagabond" => new[]
            {
                "-15 max health.",
                "-10% damage resistance.",
            },
            "Arbiter" => new[]
            {
                "-65% reload speed.",
                "-100% hipfire accuracy.",
            },
            "Executioner" => new[]
            {
                "-100% hipfire accuracy.",
                "-30% recoil control.",
            },
            "Berserker" => new[]
            {
                "-100% recoil control.",
                "-65% reload speed.",
            },
            "Artillerist" => new[]
            {
                "-15% damage resistance.",
                "-25% shove speed.",
            },
            "Riskrunner" => new[]
            {
                "Inability to aim ranged weapons.",
                "Scavenge ~75% (4x) less ammo.",
                "-10% walkspeed.",
            },
            "Hivemind" => new[]
            {
                "-15 max health.",
                "-20% recoil control.",
                "-20 max stamina.",
            },
            "Blitzer" => new[]
            {
                "-15% melee damage.",
                "-50% trap deployment speed.",
            },
            "Tickspider" => new[]
            {
                "-10% walkspeed.",
                "-15% melee damage.",
            },
            "Crosslink" => new[]
            {
                "-10% melee damage.",
                "-20% damage resistance.",
            },
            _ => Array.Empty<string>(),
        };
    }

    private Button MakePerkTileButton(PerkInfo perk)
    {
        var btn = new Button
        {
            HorizontalAlignment = HAlignment.Center,
            VerticalAlignment = VAlignment.Center,
        };

        var iconRect = new TextureRect
        {
            Texture = _resourceCache.GetTexture(PerkIconDir + perk.Icon + ".png"),
            Stretch = TextureRect.StretchMode.KeepAspectCovered,
            HorizontalExpand = true,
            VerticalExpand = true,
            HorizontalAlignment = HAlignment.Center,
            VerticalAlignment = VAlignment.Center,
        };
        btn.AddChild(iconRect);
        return btn;
    }

    private void PerkTileHover(Button btn, bool hovering)
    {
        if (!_perkPickData.TryGetValue(btn, out var perk))
            return;

        if (hovering)
            _hoveredPerkTile = btn;
        else if (ReferenceEquals(_hoveredPerkTile, btn))
            _hoveredPerkTile = null;

        if (!hovering && _selectedPerk != perk)
        {
            ClearPerksInfo();
            return;
        }

        _showPerkInfo = true;
        PerksInfoNameLabel.Text = perk.Name;
        PerksInfoDescLabel.SetMessage($"{perk.Description}");
        PerksInfoProsLabel.SetMessage(FormatPerkLines(perk.Pros, "8CFF9E"));
        PerksInfoConsLabel.SetMessage(FormatPerkLines(perk.Cons, "FF9A9A"));
        PerksProsHeaderLabel.Visible = perk.Pros.Count > 0;
        PerksInfoProsLabel.Visible = perk.Pros.Count > 0;
        PerksConsHeaderLabel.Visible = perk.Cons.Count > 0;
        PerksInfoConsLabel.Visible = perk.Cons.Count > 0;
    }

    private void ClearPerksInfo()
    {
        _showPerkInfo = false;
        PerksInfoNameLabel.Text = "—";
        PerksInfoDescLabel.SetMessage("");
        PerksInfoProsLabel.SetMessage("");
        PerksInfoConsLabel.SetMessage("");
        PerksProsHeaderLabel.Visible = true;
        PerksInfoProsLabel.Visible = true;
        PerksConsHeaderLabel.Visible = true;
        PerksInfoConsLabel.Visible = true;
    }

    private static string FormatPerkLines(IReadOnlyList<string> lines, string color)
    {
        if (lines == null || lines.Count == 0)
            return string.Empty;
        var markup = new System.Text.StringBuilder();
        for (var i = 0; i < lines.Count; i++)
        {
            markup.Append($"[color=#{color}]• {lines[i]}[/color]");
            if (i < lines.Count - 1)
                markup.AppendLine();
        }
        return markup.ToString();
    }

    private void OnPerkPick(Button btn)
    {
        if (!_perkPickData.TryGetValue(btn, out var perk))
            return;

        _selectedPerk = ReferenceEquals(_selectedPerk, perk) ? null : perk;

        foreach (var b in _perkBtns)
        {
            var sel = _selectedPerk != null && ReferenceEquals(_selectedPerk, _perkPickData[b]);
            if (sel && _perkSelectedStyle.TryGetValue(b, out var selectBox))
                b.StyleBoxOverride = selectBox;
            else if (_perkStyle.TryGetValue(b, out var normalBox))
                b.StyleBoxOverride = normalBox;
        }

        RefreshPerksCount();
        PerkTileHover(btn, false);
    }

    private void RefreshPerksCount()
    {
    }

    private void UpdatePerksHoverHighlight(float delta)
    {
        if (_perkBtns.Count == 0)
            return;

        var ease = 1f - MathF.Exp(-14f * Math.Max(delta, 0.016f));

        var viewport = Math.Max(PerksScroll.Size.Y, 1f);
        var scroll = PerksScroll.VScroll;
        const float baseS = 92f;
        const float sep = 12f;
        const float stride = baseS + sep;
        var halfSpan = Math.Max(viewport * 0.78f, 1f);
        var focus = scroll + viewport / 2f;

        var available = Math.Max(PerksScroll.Size.X - 16f, 1f);

        for (var i = 0; i < _perkBtns.Count; i++)
        {
            var b = _perkBtns[i];
            var rowCenter = i * stride + stride / 2f;
            var t = Math.Clamp(Math.Abs(rowCenter - focus) / halfSpan, 0f, 1f);
            t = t * t * (3f - 2f * t);

            var engagedNow = ReferenceEquals(b, _hoveredPerkTile)
                || (_selectedPerk != null && ReferenceEquals(_selectedPerk, _perkPickData[b]));

            _perkEngaged.TryGetValue(b, out var curE);
            var targetE = engagedNow ? 1f : 0f;
            var e = curE + (targetE - curE) * ease;
            _perkEngaged[b] = e;

            var effT = Math.Clamp(t * (1f - 0.92f * e), 0f, 1f);

            var bright = 1.12f - effT * 0.45f;
            b.Modulate = new Color(bright, bright, bright, 1f);

            var height = baseS * (1f + 0.45f * (1f - effT));
            var width = Math.Max(available * (1f - effT * 0.28f), 32f);
            var popUp = (1f - effT) * 6f;

            b.HorizontalAlignment = HAlignment.Center;
            b.MinSize = new Vector2(width, height);
            b.MaxSize = new Vector2(width, height);
            b.Margin = new Thickness(0, -popUp, 0, popUp);
        }

        var infoTarget = _showPerkInfo ? 1f : 0f;
        _perkInfoAnim += (infoTarget - _perkInfoAnim) * ease;
        var animA = Math.Clamp(_perkInfoAnim, 0f, 1f);
        PerksInfoPanel.Modulate = new Color(1f, 1f, 1f, animA);
    }

    private void BuildPerksMenu()
    {
        PerkArcContainer.RemoveAllChildren();
        _perkBtns.Clear();
        _perkPickData.Clear();
        _perkStyle.Clear();
        _perkSelectedStyle.Clear();

        _perksInfoBox = new ScrollingScanlineStyleBox
        {
            Texture = _scanlineTexture,
            BackgroundColor = Color.FromHex("#4a82bf"),
            BorderColor = Color.FromHex("#bfe3ff").WithAlpha(0.7f),
            BorderThickness = 1.5f,
            InwardLean = 0.05f,
        };
        PerksInfoPanel.PanelOverride = _perksInfoBox;

        foreach (var (icon, name) in PerkSeeds())
        {
            var perk = new PerkInfo
            {
                Icon = icon,
                Name = name,
                Description = PerksFlavor(name),
                Pros = new List<string>(PerkPros(name)),
                Cons = new List<string>(PerkCons(name)),
            };
            var tile = MakePerkTileButton(perk);
            _perkBtns.Add(tile);
            _perkPickData[tile] = perk;

            var normal = new ScrollingScanlineStyleBox
            {
                Texture = _scanlineTexture,
                BackgroundColor = Color.FromHex("#4a82bf"),
                BorderColor = Color.FromHex("#bfe3ff").WithAlpha(0.7f),
                BorderThickness = 1.5f,
                InwardLean = 0.05f,
            };
            var selectedBox = new ScrollingScanlineStyleBox
            {
                Texture = _scanlineTexture,
                BackgroundColor = Color.FromHex("#eefbff"),
                BorderColor = Color.FromHex("#ffffff"),
                BorderThickness = 3f,
                InwardLean = 0.05f,
            };

            _perkStyle[tile] = normal;
            _perkSelectedStyle[tile] = selectedBox;
            tile.StyleBoxOverride = normal;

            tile.OnPressed += _ => OnPerkPick(tile);
            tile.OnMouseEntered += _ => PerkTileHover(tile, true);
            tile.OnMouseExited += _ => PerkTileHover(tile, false);

            PerkArcContainer.AddChild(tile);
        }

        RefreshPerksCount();
        UpdatePerksHoverHighlight(0.016f);
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);
    }
}
