using System;
using System.Collections.Generic;
using System.Linq;
using System.Numerics;
using Content.Client.Humanoid;
using Content.Client.Lobby;
using Content.Client.Lobby.UI.ProfileEditorControls;
using Content.Client.Resources;
using Content.Shared.Body;
using Content.Shared.Chat.Prototypes;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Markings;
using Content.Shared.Humanoid.Prototypes;
using Content.Shared.Preferences;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.Utility;
using Robust.Shared.Enums;
using Robust.Shared.Utility;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using Direction = Robust.Shared.Maths.Direction;

namespace Content.Client._Nivalis.UserInterface.Lobby;

[GenerateTypedNameReferences]
public sealed partial class NivalisCharacterCustomization : LayoutContainer
{
    [Dependency] private IClientPreferencesManager _preferences = default!;
    [Dependency] private IEntityManager _entity = default!;
    [Dependency] private IPrototypeManager _proto = default!;
    [Dependency] private IResourceCache _resCache = default!;
    [Dependency] private MarkingManager _marking = default!;
    [Dependency] private ILocalizationManager _loc = default!;

    private SpriteSystem? _sprite;

    private SpriteSystem Sprite => _sprite ??= _entity.System<SpriteSystem>();

    private static readonly ProtoId<SpeciesPrototype> ForcedSpecies = "Felinid";

    public event Action? Closed;

    public HumanoidCharacterProfile? Profile;

    public int? CharacterSlot;

    private readonly MarkingsViewModel _markingsModel = new();

    private Font _displayBold = default!;
    private Font _displayRegular = default!;
    private Font _displaySmall = default!;

    private Texture? _scanlineTexture;

    private Direction _previewRotation = Direction.North;

    private readonly List<(string Id, string Label, Button Button)> _categories = new();
    private readonly Dictionary<Button, ScrollingScanlineStyleBox> _catStyle = new();
    private readonly Dictionary<Button, bool> _catHover = new();
    private readonly Dictionary<Button, float> _catHoverAmount = new();
    private Button? _activeCategory;

    private string _activeCategoryId = "identity";

    private readonly List<Button> _markingTiles = new();
    private Button? _noneTile;
    private readonly Dictionary<Button, MarkingTileData> _markingTileData = new();
    private readonly Dictionary<Button, ScrollingScanlineStyleBox> _markingStyle = new();
    private readonly Dictionary<Button, ScrollingScanlineStyleBox> _markingSelectedStyle = new();
    private readonly Dictionary<Button, float> _markingEngaged = new();
    private Button? _hoveredMarkingTile;

    private ProtoId<OrganCategoryPrototype> _activeOrgan;
    private HumanoidVisualLayers _activeLayer;
    private bool _hasActiveLayer;

    private readonly ScrollingScanlineStyleBox _panelStyle = new();
    private readonly ScrollingScanlineStyleBox _contentStyle = new();

    private BoxContainer? _markingColorContainer;

    private Control? _anchorControl;

    private sealed class MarkingTileData
    {
        public MarkingPrototype Prototype = default!;
        public ProtoId<OrganCategoryPrototype> Organ;
        public HumanoidVisualLayers Layer;
    }

    private static readonly Dictionary<string, HumanoidVisualLayers> MarkingCategories = new()
    {
        ["hair"] = HumanoidVisualLayers.Hair,
        ["facialhair"] = HumanoidVisualLayers.FacialHair,
        ["tail"] = HumanoidVisualLayers.Tail,
        ["ears"] = HumanoidVisualLayers.HeadTop,
    };

    private const float HoverLerpSpeed = 9f;
    private const float IdleScrollSpeed = 9f;
    private const float HoverScrollSpeed = 26f;
    private const float NavSlantPixels = 7f;

    public NivalisCharacterCustomization()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        _displayBold = _resCache.GetFont("/Fonts/Orbitron/Orbitron-Bold.ttf", 28);
        _displayRegular = _resCache.GetFont("/Fonts/Orbitron/Orbitron-Regular.ttf", 15);
        _displaySmall = _resCache.GetFont("/Fonts/Orbitron/Orbitron-Regular.ttf", 11);

        _scanlineTexture = NivalisLobbyControl.GenerateScanlines();

        LayoutContainer.SetAnchorPreset(RootElement, LayoutContainer.LayoutPreset.Wide);
        LayoutContainer.SetAnchorPreset(Dimmer, LayoutContainer.LayoutPreset.Wide);
        LayoutContainer.SetAnchorPreset(MenuFrame, LayoutContainer.LayoutPreset.TopLeft);

        LayoutContainer.SetAnchorPreset(ContentScroll, LayoutContainer.LayoutPreset.Wide);
        LayoutContainer.SetAnchorPreset(FadeTop, LayoutContainer.LayoutPreset.TopWide);
        LayoutContainer.SetAnchorPreset(FadeBottom, LayoutContainer.LayoutPreset.BottomWide);

        MouseFilter = MouseFilterMode.Ignore;
        RootElement.MouseFilter = MouseFilterMode.Ignore;
        Dimmer.MouseFilter = MouseFilterMode.Ignore;

        TitleLabel.FontOverride = _displayBold;
        SubtitleLabel.FontOverride = _displayRegular;
        AgentTitleLabel.FontOverride = _displayRegular;
        AgentNameLabel.FontOverride = _displayRegular;

        TitleLabel.Text = Loc.GetString("nivalis-customization-title");
        SubtitleLabel.Text = Loc.GetString("nivalis-customization-subtitle");
        AgentTitleLabel.Text = Loc.GetString("nivalis-customization-agent-title");
        AgentNameLabel.Text = Loc.GetString("nivalis-customization-unknown");
        SaveButton.Text = Loc.GetString("nivalis-customization-save");
        ResetButton.Text = Loc.GetString("nivalis-customization-reset");

        _panelStyle.Texture = _scanlineTexture;
        _panelStyle.BackgroundColor = new Color(3, 6, 13, 252);
        _panelStyle.BorderColor = Color.FromHex("#3E7FB0").WithAlpha(0.55f);
        _panelStyle.BorderThickness = 1.25f;
        MenuFrame.PanelOverride = _panelStyle;

        _contentStyle.Texture = _scanlineTexture;
        _contentStyle.BackgroundColor = new Color(1, 3, 8, 235);
        _contentStyle.BorderColor = Color.FromHex("#1c3a5c").WithAlpha(0.85f);
        _contentStyle.BorderThickness = 1f;
        ContentPanel.PanelOverride = _contentStyle;

        FadeTop.Texture = GenerateFadeTexture(topToBottom: true);
        FadeBottom.Texture = GenerateFadeTexture(topToBottom: false);

        _markingsModel.MarkingsReset += OnMarkingsReset;
        _markingsModel.MarkingsChanged += OnMarkingsChanged;

        BuildCategories();
        SetupFooter();

        SaveButton.OnPressed += _ => Save();
        ResetButton.OnPressed += _ => ReloadFromPreferences();

        RotateLeft.OnPressed += _ =>
        {
            _previewRotation = _previewRotation.TurnCw();
            SetPreviewRotation(_previewRotation);
        };
        RotateRight.OnPressed += _ =>
        {
            _previewRotation = _previewRotation.TurnCcw();
            SetPreviewRotation(_previewRotation);
        };
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();

        _markingsModel.MarkingsReset -= OnMarkingsReset;
        _markingsModel.MarkingsChanged -= OnMarkingsChanged;
    }

    public void SetAnchorControl(Control anchor)
    {
        _anchorControl = anchor;
        PositionMenu();
    }

    private void PositionMenu()
    {
        if (Parent == null)
            return;

        var parentSize = Parent.Size;
        if (parentSize.X <= 2 || parentSize.Y <= 2)
            return;

        MenuFrame.Measure(parentSize);
        var size = MenuFrame.DesiredSize;

        var anchorX = _anchorControl?.GlobalPosition.X + _anchorControl?.Width ?? 410f;
        var anchorCenterY = _anchorControl != null
            ? _anchorControl.GlobalPosition.Y + _anchorControl.Height / 2f
            : parentSize.Y / 2f;

        var left = anchorX + 16f;
        var top = anchorCenterY - size.Y / 2f;

        left = Math.Clamp(left, 14f, Math.Max(14f, parentSize.X - size.X - 14f));
        top = Math.Clamp(top, 14f, Math.Max(14f, parentSize.Y - size.Y - 14f));

        LayoutContainer.SetMarginLeft(MenuFrame, left);
        LayoutContainer.SetMarginTop(MenuFrame, top);
    }

    private void SetupFooter()
    {
        foreach (var button in new[] { SaveButton, ResetButton })
        {
            var style = new ScrollingScanlineStyleBox
            {
                Texture = _scanlineTexture,
                BackgroundColor = Color.FromHex("#0a1526"),
                BorderColor = Color.FromHex("#244a75").WithAlpha(0.9f),
                BorderThickness = 1.25f,
                SlantPixels = NavSlantPixels,
            };
            button.StyleBoxOverride = style;
            _catStyle[button] = style;
            _catHover[button] = false;
            _catHoverAmount[button] = 0f;
            button.OnMouseEntered += _ => _catHover[button] = true;
            button.OnMouseExited += _ => _catHover[button] = false;
        }

        foreach (var button in new[] { RotateLeft, RotateRight })
        {
            var style = new ScrollingScanlineStyleBox
            {
                Texture = _scanlineTexture,
                BackgroundColor = Color.FromHex("#0a1526"),
                BorderColor = Color.FromHex("#244a75").WithAlpha(0.9f),
                BorderThickness = 1.25f,
                SlantPixels = 0f,
            };
            if (button is SlantedButton slanted)
                slanted.Shear = 0f;
            button.StyleBoxOverride = style;
            _catStyle[button] = style;
            _catHover[button] = false;
            _catHoverAmount[button] = 0f;
            button.OnMouseEntered += _ => _catHover[button] = true;
            button.OnMouseExited += _ => _catHover[button] = false;
        }
    }

    private void ReloadFromPreferences()
    {
        SetProfile(
            _preferences.Preferences?.SelectedCharacter as HumanoidCharacterProfile,
            _preferences.Preferences?.SelectedCharacterIndex);
    }

    private void BuildCategories()
    {
        CategoryNav.RemoveAllChildren();
        _categories.Clear();
        _catStyle.Clear();

        AddCategory("identity", Loc.GetString("nivalis-customization-category-identity"));
        AddCategory("body", Loc.GetString("nivalis-customization-category-body"));
        AddCategory("hair", Loc.GetString("nivalis-customization-category-hair"));
        AddCategory("facialhair", Loc.GetString("nivalis-customization-category-facialhair"));
        AddCategory("tail", Loc.GetString("nivalis-customization-category-tail"));
        AddCategory("ears", Loc.GetString("nivalis-customization-category-ears"));

        if (_categories.Count > 0)
            SelectCategory(_categories[0]);
    }

    private void AddCategory(string id, string label)
    {
        var button = new SlantedButton
        {
            Text = label,
            HorizontalExpand = false,
            HorizontalAlignment = Control.HAlignment.Left,
            MinSize = new Vector2(200, 30),
            Margin = new Thickness(_categories.Count * 4, 0, 0, 3),
        };

        var style = new ScrollingScanlineStyleBox
        {
            Texture = _scanlineTexture,
            BackgroundColor = Color.FromHex("#0a1526"),
            BorderColor = Color.FromHex("#244a75").WithAlpha(0.9f),
            BorderThickness = 1.25f,
            SlantPixels = NavSlantPixels,
        };
        button.StyleBoxOverride = style;
        _catStyle[button] = style;
        _catHover[button] = false;
        _catHoverAmount[button] = 0f;

        button.OnPressed += _ => SelectCategory((id, label, button));
        button.OnMouseEntered += _ => _catHover[button] = true;
        button.OnMouseExited += _ => _catHover[button] = false;

        _categories.Add((id, label, button));
        CategoryNav.AddChild(button);
    }

    private void SelectCategory((string Id, string Label, Button Button) category)
    {
        _activeCategory = category.Button;
        _activeCategoryId = category.Id;

        foreach (var (_, _, button) in _categories)
        {
            if (button == _activeCategory)
                _catStyle[button].Modulate = Color.White;
            else
                _catStyle[button].Modulate = Color.FromHex("#8FA3B8");
        }

        BuildCategoryContent();
    }

    private void BuildCategoryContent()
    {
        ContentBody.RemoveAllChildren();
        _markingTiles.Clear();
        _markingTileData.Clear();
        _markingStyle.Clear();
        _markingSelectedStyle.Clear();
        _markingEngaged.Clear();
        _markingColorContainer = null;

        _hoveredMarkingTile = null;
        _hasActiveLayer = false;

        switch (_activeCategoryId)
        {
            case "identity":
                BuildIdentity();
                break;
            case "body":
                BuildBody();
                break;
            default:
                if (MarkingCategories.TryGetValue(_activeCategoryId, out var layer))
                    BuildMarkingCategory(layer);
                break;
        }
    }

    #region Identity

    private LineEdit? _nameEdit;
    private LineEdit? _ageEdit;
    private NivalisDropdown? _sexButton;
    private NivalisDropdown? _pronounsButton;



    private void BuildIdentity()
    {
        _nameEdit = AddTextRow("NAME", Profile?.Name ?? string.Empty, text => SetName(text));
        _nameEdit.MinSize = new Vector2(220, 0);

        _ageEdit = AddTextRow("AGE", Profile?.Age.ToString() ?? "0", text =>
        {
            if (int.TryParse(text, out var age))
                SetAge(age);
        });
        _ageEdit.MinSize = new Vector2(80, 0);

        _sexButton = AddDropdownRow("SEX", out _);
        RefreshSex();
        _sexButton.OnItemSelected += args =>
        {
            _sexButton.SelectId(args.Id);
            SetSex((Sex)args.Id);
        };

        _pronounsButton = AddDropdownRow("PRONOUNS", out _);
        _pronounsButton.AddItem(Loc.GetString("humanoid-profile-editor-pronouns-male-text"), (int)Gender.Male);
        _pronounsButton.AddItem(Loc.GetString("humanoid-profile-editor-pronouns-female-text"), (int)Gender.Female);
        _pronounsButton.AddItem(Loc.GetString("humanoid-profile-editor-pronouns-epicene-text"), (int)Gender.Epicene);
        _pronounsButton.AddItem(Loc.GetString("humanoid-profile-editor-pronouns-neuter-text"), (int)Gender.Neuter);
        if (Profile != null)
            _pronounsButton.SelectId((int)Profile.Gender);
        _pronounsButton.OnItemSelected += args =>
        {
            _pronounsButton.SelectId(args.Id);
            SetGender((Gender)args.Id);
        };
    }

    private LineEdit AddTextRow(string label, string value, Action<string> onChanged)
    {
        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            VerticalAlignment = Control.VAlignment.Center,
        };
        row.AddChild(MakeLabel(label, _displayRegular, "#8FA3B8"));
        row.AddChild(new Control { HorizontalExpand = true });
        var edit = new LineEdit
        {
            Text = value,
            HorizontalAlignment = Control.HAlignment.Right,
            VerticalAlignment = Control.VAlignment.Center,
            MinSize = new Vector2(200, 0),
        };
        edit.OnTextChanged += args => onChanged(args.Text);
        row.AddChild(edit);
        ContentBody.AddChild(row);
        return edit;
    }

    private NivalisDropdown AddDropdownRow(string label, out BoxContainer row)
    {
        row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            VerticalAlignment = Control.VAlignment.Center,
        };
        row.AddChild(MakeLabel(label, _displayRegular, "#8FA3B8"));
        row.AddChild(new Control { HorizontalExpand = true });
        var dropdown = new NivalisDropdown
        {
            HorizontalAlignment = Control.HAlignment.Right,
            VerticalAlignment = Control.VAlignment.Center,
            ScanlineTexture = _scanlineTexture,
            FontOverride = _displaySmall,
        };
        row.AddChild(dropdown);
        ContentBody.AddChild(row);
        return dropdown;
    }

    private static Label MakeLabel(string text, Font font, string? color = null)
    {
        var label = new Label { Text = text, FontOverride = font, VerticalAlignment = Control.VAlignment.Center };
        if (color != null)
            label.FontColorOverride = Color.FromHex(color);
        return label;
    }

    private string MarkingName(string markingId)
    {
        var key = $"marking-{markingId}";
        return _loc.TryGetString(key, out var value) ? value : HumanizeId(markingId);
    }

    private string MarkingLayerName(string markingId, string layerState)
    {
        var key = $"marking-{markingId}-{layerState}";
        return _loc.TryGetString(key, out var value) ? value : HumanizeId(layerState);
    }

    private static string HumanizeId(string id)
    {
        var builder = new System.Text.StringBuilder(id.Length + 8);
        for (var i = 0; i < id.Length; i++)
        {
            var c = id[i];
            if (c is '_' or '-')
            {
                builder.Append(' ');
                continue;
            }

            if (i > 0 && char.IsUpper(c) && !char.IsUpper(id[i - 1]))
                builder.Append(' ');

            builder.Append(c);
        }

        return builder.ToString();
    }

    private void SetName(string name)
    {
        if (Profile == null)
            return;
        Profile = Profile.WithName(name);
        AgentNameLabel.Text = name;
        PreviewSprite.SetName(name);
    }

    private void SetAge(int age)
    {
        if (Profile == null)
            return;
        Profile = Profile.WithAge(age);
        ReloadPreview();
    }

    private void SetSex(Sex sex)
    {
        if (Profile == null)
            return;

        Profile = Profile.WithSex(sex);
        Profile = sex switch
        {
            Sex.Male => Profile.WithGender(Gender.Male),
            Sex.Female => Profile.WithGender(Gender.Female),
            _ => Profile.WithGender(Gender.Epicene),
        };

        if (_proto.TryIndex(Profile.Species, out SpeciesPrototype? speciesProto))
            SetVoice(speciesProto.DefaultSoundsBySex[(int)sex]);

        _markingsModel.SetOrganSexes(sex);
        _markingsModel.ValidateMarkings();
        Profile = Profile.WithCharacterAppearance(Profile.Appearance.WithMarkings(_markingsModel.Markings));

        if (_pronounsButton != null)
            _pronounsButton.SelectId((int)Profile.Gender);

        BuildCategoryContent();
        ReloadPreview();
    }

    private void SetVoice(ProtoId<EmoteSoundsPrototype> voice)
    {
        Profile = Profile?.WithVoice(voice);
    }

    private void SetGender(Gender gender)
    {
        Profile = Profile?.WithGender(gender);
        ReloadPreview();
    }

    private void RefreshSex()
    {
        if (_sexButton == null || Profile == null)
            return;

        _sexButton.Clear();
        var sexes = new List<Sex>();
        if (_proto.TryIndex(Profile.Species, out SpeciesPrototype? speciesProto))
            sexes.AddRange(speciesProto.Sexes);
        else
            sexes.Add(Sex.Unsexed);

        foreach (var sex in sexes)
            _sexButton.AddItem(Loc.GetString($"humanoid-profile-editor-sex-{sex.ToString().ToLower()}-text"), (int)sex);

        if (sexes.Contains(Profile.Sex))
            _sexButton.SelectId((int)Profile.Sex);
        else if (sexes.Count > 0)
            _sexButton.SelectId((int)sexes[0]);
    }

    #endregion Identity

    #region Body

    private NivalisSlider? _skinSlider;
    private NivalisColorSliders? _rgbSkinSelector;
    private BoxContainer? _rgbSkinContainer;
    private NivalisColorSliders? _eyeColorPicker;

    private void BuildBody()
    {
        ContentBody.AddChild(MakeLabel("SKIN COLOR", _displayRegular, "#8FA3B8"));
        _skinSlider = new NivalisSlider { MinValue = 0, MaxValue = 100, HorizontalExpand = true, ScanlineTexture = _scanlineTexture };
        _skinSlider.OnValueCommitted += _ => OnSkinColorChanged();
        ContentBody.AddChild(_skinSlider);

        _rgbSkinContainer = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Vertical, Visible = false, HorizontalExpand = true };
        _rgbSkinSelector = new NivalisColorSliders { ScanlineTexture = _scanlineTexture };
        _rgbSkinSelector.OnColorChanged += _ => OnSkinColorChanged();
        _rgbSkinContainer.AddChild(_rgbSkinSelector);
        ContentBody.AddChild(_rgbSkinContainer);

        ContentBody.AddChild(new Control { MinSize = new Vector2(0, 6) });
        ContentBody.AddChild(MakeLabel("EYE COLOR", _displayRegular, "#8FA3B8"));
        _eyeColorPicker = new NivalisColorSliders { ScanlineTexture = _scanlineTexture };
        _eyeColorPicker.OnColorChanged += color =>
        {
            if (Profile == null)
                return;
            Profile = Profile.WithCharacterAppearance(Profile.Appearance.WithEyeColor(color));
            _markingsModel.SetOrganEyeColor(color);
            ReloadPreview();
        };
        ContentBody.AddChild(_eyeColorPicker);

        UpdateSkinControls();
        UpdateEyePicker();
    }

    private void UpdateSkinControls()
    {
        if (Profile == null || _skinSlider == null || _rgbSkinContainer == null || _rgbSkinSelector == null)
            return;

        var skin = _proto.Index<SpeciesPrototype>(Profile.Species).SkinColoration;
        var strategy = _proto.Index(skin).Strategy;

        switch (strategy.InputType)
        {
            case SkinColorationStrategyInput.Unary:
                _skinSlider.Visible = true;
                _rgbSkinContainer.Visible = false;
                _skinSlider.Value = strategy.ToUnary(Profile.Appearance.SkinColor);
                break;
            case SkinColorationStrategyInput.Color:
                _skinSlider.Visible = false;
                _rgbSkinContainer.Visible = true;
                _rgbSkinSelector.Color = strategy.ClosestSkinColor(Profile.Appearance.SkinColor);
                break;
        }
    }

    private void UpdateEyePicker()
    {
        if (Profile == null || _eyeColorPicker == null)
            return;
        _markingsModel.SetOrganEyeColor(Profile.Appearance.EyeColor);
        _eyeColorPicker.Color = Profile.Appearance.EyeColor;
    }

    private void OnSkinColorChanged()
    {
        if (Profile == null)
            return;

        var skin = _proto.Index<SpeciesPrototype>(Profile.Species).SkinColoration;
        var strategy = _proto.Index(skin).Strategy;

        Color color;
        switch (strategy.InputType)
        {
            case SkinColorationStrategyInput.Unary:
                color = strategy.FromUnary(_skinSlider!.Value);
                _markingsModel.SetOrganSkinColor(color);
                Profile = Profile.WithCharacterAppearance(Profile.Appearance.WithSkinColor(color));
                break;
            case SkinColorationStrategyInput.Color:
                color = strategy.ClosestSkinColor(_rgbSkinSelector!.Color);
                _markingsModel.SetOrganSkinColor(color);
                Profile = Profile.WithCharacterAppearance(Profile.Appearance.WithSkinColor(color));
                break;
            default:
                return;
        }

        PreviewSprite.ReloadProfilePreview(Profile);
    }

    #endregion Body

    #region Markings (hair / facial hair / tail / ears)

    private void BuildMarkingCategory(HumanoidVisualLayers layer)
    {
        var organs = _marking.GetMarkingData(Profile?.Species ?? ForcedSpecies);
        ProtoId<OrganCategoryPrototype>? matchedOrgan = null;
        foreach (var (organ, data) in organs)
        {
            if (data.Layers.Contains(layer))
            {
                matchedOrgan = organ;
                break;
            }
        }

        if (matchedOrgan == null)
        {
            ContentBody.AddChild(MakeLabel(Loc.GetString("nivalis-customization-no-species-options"), _displaySmall, "#8FA3B8"));
            return;
        }

        var organId = matchedOrgan.Value;
        var organData = organs[organId];

        if (!_markingsModel.OrganProfileData.TryGetValue(organId, out var profileData))
        {
            ContentBody.AddChild(MakeLabel("NO ORGAN DATA AVAILABLE.", _displaySmall, "#8FA3B8"));
            return;
        }

        var allMarkings = _markingsModel.EnforceGroupAndSexRestrictions
            ? _marking.MarkingsByLayerAndGroupAndSex(layer, organData.Group, profileData.Sex)
            : _marking.MarkingsByLayer(layer);

        _activeOrgan = organId;
        _activeLayer = layer;
        _hasActiveLayer = true;

        if (allMarkings.Count == 0)
        {
            ContentBody.AddChild(MakeLabel(Loc.GetString("nivalis-customization-no-options"), _displaySmall, "#8FA3B8"));
            return;
        }

        var grid = new GridContainer { Columns = 4, HorizontalExpand = true };
        ContentBody.AddChild(grid);

        var noneButton = new SlantedButton
        {
            Text = Loc.GetString("nivalis-customization-none"),
            MinSize = new Vector2(96, 96),
            MaxSize = new Vector2(96, 96),
            HorizontalAlignment = Control.HAlignment.Center,
            VerticalAlignment = Control.VAlignment.Center,
        };
        var noneStyle = new ScrollingScanlineStyleBox
        {
            Texture = _scanlineTexture,
            BackgroundColor = Color.FromHex("#101d33"),
            BorderColor = Color.FromHex("#3E7FB0").WithAlpha(0.6f),
            BorderThickness = 1.5f,
            InwardLean = 0.05f,
            SlantPixels = NavSlantPixels,
        };
        noneButton.StyleBoxOverride = noneStyle;
        noneButton.OnMouseEntered += _ => noneButton.VisualScale = new Vector2(1.005f, 1.005f);
        noneButton.OnMouseExited += _ => noneButton.VisualScale = Vector2.One;
        noneButton.OnPressed += _ => ClearCurrentLayer();
        grid.AddChild(noneButton);
        _noneTile = noneButton;

        foreach (var marking in allMarkings.Values.OrderBy(m => MarkingName(m.ID)))
        {
            var tile = MakeMarkingTile(organId, layer, marking);
            grid.AddChild(tile);
        }

        _markingColorContainer = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
            SeparationOverride = 6,
            Margin = new Thickness(0, 8, 0, 0),
        };
        ContentBody.AddChild(_markingColorContainer);

        UpdateMarkingTilesVisual(0.016f);
        RefreshMarkingColors();
    }

    private void ClearMarkingLayer(HumanoidVisualLayers layer)
    {
        var organs = _marking.GetMarkingData(Profile?.Species ?? ForcedSpecies);
        foreach (var (organ, data) in organs)
        {
            if (!data.Layers.Contains(layer))
                continue;

            var selected = _markingsModel.SelectedMarkings(organ, layer);
            if (selected == null)
                continue;

            var previousLimits = _markingsModel.EnforceLimits;
            _markingsModel.EnforceLimits = false;
            foreach (var marking in selected.ToList())
                _markingsModel.TryDeselectMarking(organ, layer, marking.MarkingId);
            _markingsModel.EnforceLimits = previousLimits;
        }
    }

    private void ClearCurrentLayer()
    {
        if (!_hasActiveLayer)
            return;

        var current = _markingsModel.SelectedMarkings(_activeOrgan, _activeLayer);
        if (current == null)
            return;

        var previousLimits = _markingsModel.EnforceLimits;
        _markingsModel.EnforceLimits = false;
        foreach (var marking in current.ToList())
            _markingsModel.TryDeselectMarking(_activeOrgan, _activeLayer, marking.MarkingId);
        _markingsModel.EnforceLimits = previousLimits;

        RefreshMarkingColors();
    }

    private Button MakeMarkingTile(ProtoId<OrganCategoryPrototype> organ, HumanoidVisualLayers layer, MarkingPrototype prototype)
    {
        var tile = new SlantedButton
        {
            MinSize = new Vector2(96, 96),
            MaxSize = new Vector2(96, 96),
            HorizontalAlignment = Control.HAlignment.Center,
            VerticalAlignment = Control.VAlignment.Center,
            ToolTip = MarkingName(prototype.ID),
        };

        var content = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
            VerticalExpand = true,
        };

        var texRect = new LayeredTextureRect
        {
            TextureScale = new Vector2(2, 2),
            HorizontalAlignment = Control.HAlignment.Center,
            VerticalAlignment = Control.VAlignment.Center,
            HorizontalExpand = true,
            VerticalExpand = true,
        };
        texRect.Textures = prototype.Sprites.Select(s => Sprite.Frame0(s)).ToList();
        content.AddChild(texRect);
        tile.AddChild(content);

        var normal = new ScrollingScanlineStyleBox
        {
            Texture = _scanlineTexture,
            BackgroundColor = Color.FromHex("#20375c"),
            BorderColor = Color.FromHex("#5f93c8").WithAlpha(0.7f),
            BorderThickness = 1.5f,
            InwardLean = 0.05f,
        };
        var selected = new ScrollingScanlineStyleBox
        {
            Texture = _scanlineTexture,
            BackgroundColor = Color.FromHex("#c3dbf2"),
            BorderColor = Color.FromHex("#eaf5ff"),
            BorderThickness = 3f,
            InwardLean = 0.05f,
        };

        _markingStyle[tile] = normal;
        _markingSelectedStyle[tile] = selected;
        tile.StyleBoxOverride = normal;

        _markingTiles.Add(tile);
        _markingTileData[tile] = new MarkingTileData
        {
            Prototype = prototype,
            Organ = organ,
            Layer = layer,
        };
        _markingEngaged[tile] = 0f;

        tile.OnPressed += _ => OnMarkingTilePressed(tile);
        tile.OnMouseEntered += _ => _hoveredMarkingTile = tile;
        tile.OnMouseExited += _ =>
        {
            if (ReferenceEquals(_hoveredMarkingTile, tile))
                _hoveredMarkingTile = null;
        };

        RefreshMarkingTileSelection(tile);
        return tile;
    }

    private void OnMarkingTilePressed(Button tile)
    {
        if (!_markingTileData.TryGetValue(tile, out var data))
            return;

        if (_markingsModel.IsMarkingSelected(data.Organ, data.Layer, data.Prototype.ID))
            _markingsModel.TryDeselectMarking(data.Organ, data.Layer, data.Prototype.ID);
        else
            _markingsModel.TrySelectMarking(data.Organ, data.Layer, data.Prototype.ID);

        RefreshMarkingTileSelection(tile);
        RefreshMarkingColors();
    }

    private void RefreshMarkingTileSelection(Button tile)
    {
        if (!_markingTileData.TryGetValue(tile, out var data))
            return;

        var isSelected = _markingsModel.IsMarkingSelected(data.Organ, data.Layer, data.Prototype.ID);
        tile.StyleBoxOverride = isSelected && _markingSelectedStyle.TryGetValue(tile, out var sel)
            ? sel
            : _markingStyle[tile];
    }

    private void RefreshMarkingColors()
    {
        if (_markingColorContainer == null || !_hasActiveLayer)
            return;

        _markingColorContainer.RemoveAllChildren();

        var selected = _markingsModel.SelectedMarkings(_activeOrgan, _activeLayer);

        if (_noneTile != null)
        {
            if (selected == null || selected.Count == 0)
            {
                _noneTile.StyleBoxOverride = new ScrollingScanlineStyleBox
                {
                    Texture = _scanlineTexture,
                    BackgroundColor = Color.FromHex("#c3dbf2"),
                    BorderColor = Color.FromHex("#eaf5ff"),
                    BorderThickness = 3f,
                    InwardLean = 0.05f,
                };
            }
            else
            {
                _noneTile.StyleBoxOverride = new ScrollingScanlineStyleBox
                {
                    Texture = _scanlineTexture,
                    BackgroundColor = Color.FromHex("#101d33"),
                    BorderColor = Color.FromHex("#3E7FB0").WithAlpha(0.6f),
                    BorderThickness = 1.5f,
                    InwardLean = 0.05f,
                };
            }
        }

        if (selected == null || selected.Count == 0)
            return;

        var marking = selected[^1];
        if (!_proto.TryIndex(marking.MarkingId, out MarkingPrototype? markingProto))
            return;

        if (!_markingsModel.IsMarkingColorCustomizable(_activeOrgan, _activeLayer, marking.MarkingId))
            return;

        _markingColorContainer.AddChild(MakeLabel("COLOR", _displayRegular, "#58C6E8"));

        for (var i = 0; i < markingProto.Sprites.Count && i < marking.MarkingColors.Count; i++)
        {
            var container = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                HorizontalExpand = true,
            };

            var label = markingProto.Sprites[i] switch
            {
                SpriteSpecifier.Rsi rsi => MarkingLayerName(markingProto.ID, rsi.RsiState),
                SpriteSpecifier.Texture texture => MarkingLayerName(markingProto.ID, texture.TexturePath.Filename),
                _ => $"Layer {i + 1}",
            };

            var selector = new NivalisColorSliders
            {
                ScanlineTexture = _scanlineTexture,
                Color = marking.MarkingColors[i],
            };

            var colorIndex = i;
            selector.OnColorChanged += _ =>
            {
                _markingsModel.TrySetMarkingColor(_activeOrgan, _activeLayer, marking.MarkingId, colorIndex, selector.Color);
            };

            container.AddChild(new Label { Text = label, FontOverride = _displaySmall, FontColorOverride = Color.FromHex("#8FA3B8") });
            container.AddChild(selector);
            _markingColorContainer.AddChild(container);
        }
    }

    private void OnMarkingsReset()
    {
        foreach (var tile in _markingTiles)
            RefreshMarkingTileSelection(tile);

        RefreshMarkingColors();
    }

    private void OnMarkingsChanged(ProtoId<OrganCategoryPrototype> organ, HumanoidVisualLayers layer)
    {
        if (!_hasActiveLayer || organ != _activeOrgan || layer != _activeLayer)
            return;

        foreach (var tile in _markingTiles)
            RefreshMarkingTileSelection(tile);

        if (Profile != null)
        {
            Profile = Profile.WithCharacterAppearance(Profile.Appearance.WithMarkings(_markingsModel.Markings));
            PreviewSprite.ReloadProfilePreview(Profile);
        }
    }

    private void UpdateMarkingTilesVisual(float delta)
    {
        if (_markingTiles.Count == 0)
            return;

        var ease = 1f - MathF.Exp(-14f * Math.Max(delta, 0.016f));

        foreach (var tile in _markingTiles)
        {
            if (!_markingTileData.TryGetValue(tile, out var data))
                continue;

            var engagedNow = ReferenceEquals(tile, _hoveredMarkingTile)
                || _markingsModel.IsMarkingSelected(data.Organ, data.Layer, data.Prototype.ID);

            _markingEngaged.TryGetValue(tile, out var cur);
            var targetE = engagedNow ? 1f : 0f;
            var e = cur + (targetE - cur) * ease;
            _markingEngaged[tile] = e;

            var bright = 0.92f + 0.12f * e;
            tile.Modulate = new Color(bright, bright, bright, 1f);

            var scale = 1f + 0.005f * e;
            if (tile is SlantedButton slanted)
                slanted.VisualScale = new Vector2(scale, scale);
        }
    }

    #endregion Markings

    #region Profile / Preview

    public void SetProfile(HumanoidCharacterProfile? profile, int? slot)
    {
        Profile = profile?.Clone();
        CharacterSlot = slot;

        if (Profile == null)
        {
            Profile = HumanoidCharacterProfile.DefaultWithSpecies(ForcedSpecies);
        }
        else
        {
            Profile = Profile.WithSpecies(ForcedSpecies);
        }

        AgentNameLabel.Text = Profile.Name;

        _markingsModel.OrganData = _marking.GetMarkingData(Profile.Species);
        _markingsModel.OrganProfileData = _marking.GetProfileData(
            Profile.Species,
            Profile.Sex,
            Profile.Appearance.SkinColor,
            Profile.Appearance.EyeColor);
        _markingsModel.Markings = Profile.Appearance.Markings;

        _markingsModel.ValidateMarkings();

        ClearMarkingLayer(HumanoidVisualLayers.Tail);
        ClearMarkingLayer(HumanoidVisualLayers.HeadTop);

        Profile = Profile.WithCharacterAppearance(Profile.Appearance.WithMarkings(_markingsModel.Markings));

        SetPreviewForCategory(_activeCategoryId);
        ReloadPreview();
        BuildCategoryContent();
    }

    private void SetPreviewForCategory(string category)
    {
        _previewRotation = category == "tail" ? Direction.East : Direction.North;
        SetPreviewRotation(_previewRotation);
    }

    private void ReloadPreview()
    {
        if (Profile == null)
        {
            PreviewSprite.ClearPreview();
            return;
        }

        PreviewSprite.LoadPreview(Profile);
        AgentNameLabel.Text = Profile.Name;
        SetPreviewRotation(_previewRotation);
    }

    private void SetPreviewRotation(Direction direction)
    {
        PreviewSprite.OverrideDirection = (Direction)((int)direction % 4 * 2);
    }

    private void Save()
    {
        if (Profile == null || CharacterSlot == null)
        {
            Closed?.Invoke();
            return;
        }

        if (_preferences.Preferences?.SelectedCharacterIndex != CharacterSlot)
        {
            Closed?.Invoke();
            return;
        }

        _preferences.UpdateCharacter(Profile, CharacterSlot.Value);
        Closed?.Invoke();
    }

    #endregion Profile / Preview

    #region Animation

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        PositionMenu();
        UpdateCategoryAnimations(args.DeltaSeconds);
        UpdateMarkingTilesVisual(args.DeltaSeconds);
        UpdateScrollFades();
    }

    private static Texture GenerateFadeTexture(bool topToBottom)
    {
        const int width = 8;
        const int height = 32;

        using var image = new SixLabors.ImageSharp.Image<SixLabors.ImageSharp.PixelFormats.Rgba32>(
            SixLabors.ImageSharp.Configuration.Default, width, height);
        for (var y = 0; y < height; y++)
        {
            var t = y / (float)(height - 1);
            var alpha = (1f - t) * (1f - t);
            var a = (byte)(alpha * 235);
            var pixel = new SixLabors.ImageSharp.PixelFormats.Rgba32(1, 3, 8, a);
            var row = topToBottom ? y : height - 1 - y;
            for (var x = 0; x < width; x++)
                image[x, row] = pixel;
        }

        return Texture.LoadFromImage(image, "NivalisScrollFade");
    }

    private void UpdateScrollFades()
    {
        var viewport = ContentScroll.Height;
        var content = ContentBody.DesiredSize.Y;
        var max = content - viewport;
        if (max <= 1f)
        {
            FadeTop.Visible = false;
            FadeBottom.Visible = false;
            return;
        }

        var scroll = ContentScroll.VScroll;
        const float epsilon = 1.5f;
        FadeTop.Visible = scroll > epsilon;
        FadeBottom.Visible = scroll < max - epsilon;
    }

    private void UpdateCategoryAnimations(float frameTime)
    {
        foreach (var style in _catStyle.Values)
        {
            style.ScrollOffset += frameTime * IdleScrollSpeed;
        }

        foreach (var (button, style) in _catStyle)
        {
            var amountTarget = _catHover[button] ? 1f : 0f;
            var amount = _catHoverAmount[button];
            var lerp = 1f - MathF.Exp(-HoverLerpSpeed * frameTime);
            amount += (amountTarget - amount) * lerp;
            _catHoverAmount[button] = amount;

            var speed = _catHover[button] ? HoverScrollSpeed : IdleScrollSpeed;
            style.ScrollOffset += frameTime * (speed - IdleScrollSpeed);

            if (button is SlantedButton slanted)
                slanted.VisualScale = new Vector2(1f + 0.005f * amount, 1f + 0.005f * amount);
        }

        foreach (var style in _markingStyle.Values)
            style.ScrollOffset += frameTime * IdleScrollSpeed;
        foreach (var style in _markingSelectedStyle.Values)
            style.ScrollOffset += frameTime * IdleScrollSpeed;
        _panelStyle.ScrollOffset += frameTime * IdleScrollSpeed;
        _contentStyle.ScrollOffset += frameTime * IdleScrollSpeed;
    }

    #endregion Animation
}
