using System;
using System.Collections.Generic;
using System.Numerics;
using Content.Client.GameTicking.Managers;
using Content.Client.Lobby;
using Content.Client.Lobby.UI;
using Content.Client.Lobby.UI.ProfileEditorControls;
using Content.Client.Resources;
using Content.Client.UserInterface.Systems.Chat.Widgets;
using Content.Shared.Humanoid.Prototypes;
using Content.Shared.Preferences;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.IoC;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;
using SixLabors.ImageSharp.PixelFormats;

namespace Content.Client._Nivalis.UserInterface.Lobby;

[GenerateTypedNameReferences]
public sealed partial class NivalisLobbyControl : Control
{
    public event Action<string>? NavigationPressed;

    [Dependency] private IClientPreferencesManager _preferences = default!;
    [Dependency] private IEntityManager _entityManager = default!;
    [Dependency] private IClientConsoleHost _consoleHost = default!;
    [Dependency] private IResourceCache _resourceCache = default!;
    [Dependency] private IUriOpener _uriOpener = default!;
    [Dependency] private IPrototypeManager _proto = default!;

    private readonly Dictionary<Button, ScrollingScanlineStyleBox> _navStyle = new();
    private readonly Dictionary<Button, Vector2> _navBaseSize = new();
    private readonly Dictionary<Button, Vector2> _navCurrentSize = new();
    private readonly Dictionary<Button, Vector2> _navTargetSize = new();
    private readonly Dictionary<Button, bool> _navHover = new();
    private readonly Dictionary<Button, float> _navHoverAmount = new();
    private readonly Dictionary<Button, int> _navIndex = new();

    private Button[] _navButtons = Array.Empty<Button>();

    private bool _areWeReady;
    private Texture? _scanlineTexture;

    private const float HoverScale = 1.08f;
    private const float HoverLerpSpeed = 9f;

    private const float IdleScrollSpeed = 9f;
    private const float HoverScrollSpeed = 26f;

    private const float NeighborShrinkScale = 0.96f;

    private Font _displayBold = null!;
    private Font _displayRegular = null!;

    public NivalisLobbyControl()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        _displayBold = _resourceCache.GetFont("/Fonts/Orbitron/Orbitron-Bold.ttf", 28);
        _displayRegular = _resourceCache.GetFont("/Fonts/Orbitron/Orbitron-Regular.ttf", 15);

        LayoutContainer.SetAnchorPreset(BackgroundViewport, LayoutContainer.LayoutPreset.Wide);
        LayoutContainer.SetAnchorAndMarginPreset(Header, LayoutContainer.LayoutPreset.TopWide, margin: 20);
        LayoutContainer.SetAnchorAndMarginPreset(ChatPanel, LayoutContainer.LayoutPreset.RightWide, margin: 18);
        LayoutContainer.SetAnchorAndMarginPreset(CharacterViewport, LayoutContainer.LayoutPreset.Center);
        LayoutContainer.SetAnchorAndMarginPreset(Navigation, LayoutContainer.LayoutPreset.CenterLeft, margin: 30);
        LayoutContainer.SetAnchorAndMarginPreset(ProgressionBox, LayoutContainer.LayoutPreset.BottomLeft, margin: 24);

        _scanlineTexture = GenerateScanlines();

        BackgroundViewport.Texture = null;

        TitleLabel.FontOverride = _displayBold;
        TitleLabel.Margin = new Thickness(0, 0, 0, 4);
        foreach (var label in HeaderLabels())
            label.FontOverride = _displayRegular;

        ReadyButton.OnPressed += OnReadyPressed;
        LoadoutButton.OnPressed += _ => NavigationPressed?.Invoke("loadout");
        ChallengesButton.OnPressed += _ => NavigationPressed?.Invoke("challenges");
        QuartermasterButton.OnPressed += _ => NavigationPressed?.Invoke("quartermaster");
        PatreonButton.OnPressed += _ => _uriOpener.OpenUri("https://www.patreon.com/cw/lynnite");
        SettingsButton.OnPressed += _ => NavigationPressed?.Invoke("settings");
        QuitButton.OnPressed += _ => _consoleHost.ExecuteCommand("disconnect");

        SetupNavButtons();
    }

    private IEnumerable<Label> HeaderLabels()
    {
        yield return ReadyCountValue;
        yield return ActiveCountValue;
        yield return RespawnTimerValue;
        yield return CycleValue;
        yield return LevelValue;
        yield return OdensValue;
        yield return BondsValue;
        yield return TierValue;
    }

    public void AttachChat(ChatBox chat)
    {
        chat.Orphan();
        ChatSlot.AddChild(chat);
        chat.Margin = new Thickness(2, 2, 2, 2);
        chat.MinSize = default;
        chat.HorizontalExpand = true;
        chat.VerticalExpand = true;

        chat.ChatWindowPanel.MinSize = default;
        chat.ChatWindowPanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = Color.FromHex("#1a2a3acc"),
            BorderColor = Color.FromHex("#0a162223"),
            BorderThickness = new Thickness(1, 1, 1, 1),
        };
    }
    public void HideDefaultLobby(LobbyGui lobby, ChatBox chat)
    {
        lobby.RightSide.Visible = false;
        AttachChat(chat);

        if (lobby.LobbySong.Parent is { } songParent)
            songParent.Visible = false;
    }

    private static Texture GenerateScanlines()
    {
        const int width = 64;
        const int height = 6;

        using var image = new SixLabors.ImageSharp.Image<Rgba32>(
            SixLabors.ImageSharp.Configuration.Default, width, height);
        for (var y = 0; y < height; y++)
        {
            var dark = (y == 1 || y == 3);
            byte r = 20, g = 40, b = 70, a = 0;
            if (dark)
            {
                a = 150;
                r = 30; g = 45; b = 90;
            }
            else if (y == 2)
            {
                a = 70;
                r = 160; g = 215; b = 255;
            }

            for (var x = 0; x < width; x++)
            {
                image[x, y] = new Rgba32(r, g, b, a);
            }
        }

        return Texture.LoadFromImage(image, "NivalisScanlines");
    }

    private void SetupNavButtons()
    {
        _navButtons = new[] { ReadyButton, LoadoutButton, ChallengesButton, QuartermasterButton, PatreonButton, SettingsButton, QuitButton };
        for (var i = 0; i < _navButtons.Length; i++)
        {
            var button = _navButtons[i];
            button.Margin = new Thickness(i * 5, 0, 0, 4);
            button.HorizontalExpand = false;
            button.HorizontalAlignment = HAlignment.Left;

            var baseSize = new Vector2(button.MinWidth, button.MinHeight);
            _navBaseSize[button] = baseSize;
            _navCurrentSize[button] = baseSize;
            _navTargetSize[button] = baseSize;
            _navHover[button] = false;
            _navHoverAmount[button] = 0f;
            _navIndex[button] = i;

            var scanlineBox = new ScrollingScanlineStyleBox
            {
                Texture = _scanlineTexture,
            };

            _navStyle[button] = scanlineBox;
            button.StyleBoxOverride = scanlineBox;

            button.OnMouseEntered += _ => OnNavHover(button, true);
            button.OnMouseExited += _ => OnNavHover(button, false);
        }
    }

    private void OnNavHover(Button button, bool hovering)
    {
        _navHover[button] = hovering;
    }

    private void UpdateNavAnimations(float frameTime)
    {
        var hoveredIndex = -1;
        foreach (var kvp in _navHover)
        {
            if (kvp.Value)
            {
                hoveredIndex = _navIndex[kvp.Key];
                break;
            }
        }

        foreach (var button in _navButtons)
        {
            var baseSize = _navBaseSize[button];
            var idx = _navIndex[button];
            var isHovered = idx == hoveredIndex;
            var isNeighbor = hoveredIndex >= 0 && Math.Abs(idx - hoveredIndex) == 1;

            if (isHovered)
            {
                _navTargetSize[button] = new Vector2(baseSize.X * HoverScale, baseSize.Y * HoverScale);
            }
            else if (isNeighbor)
            {
                _navTargetSize[button] = new Vector2(baseSize.X, baseSize.Y * NeighborShrinkScale);
            }
            else
            {
                _navTargetSize[button] = baseSize;
            }
        }

        foreach (var (button, style) in _navStyle)
        {
            var current = _navCurrentSize[button];
            var target = _navTargetSize[button];
            var hoverAmount = _navHoverAmount[button];

            var amountTarget = _navHover[button] ? 1f : 0f;
            var lerp = 1f - MathF.Exp(-HoverLerpSpeed * frameTime);
            var amount = hoverAmount + (amountTarget - hoverAmount) * lerp;
            _navHoverAmount[button] = amount;

            var newSize = new Vector2(
                current.X + (target.X - current.X) * lerp,
                current.Y + (target.Y - current.Y) * lerp);
            _navCurrentSize[button] = newSize;
            button.MinSize = newSize;

            var speed = _navHover[button] ? HoverScrollSpeed : IdleScrollSpeed;
            style.ScrollOffset += frameTime * speed;

            var bright = 0.82f + 0.15f * amount;
            style.Modulate = new Color(bright, bright, bright, 1f);
        }
    }

    private void OnReadyPressed(BaseButton.ButtonEventArgs args)
    {
        var ticker = _entityManager.System<ClientGameTicker>();
        var newState = !ticker.AreWeReady;
        _consoleHost.ExecuteCommand($"toggleready {newState}");
        SetReadyState(newState);
    }

    public void SetReadyState(bool ready)
    {
        _areWeReady = ready;
        ReadyButton.Text = ready ? "READY" : "NOT READY";
    }

    public void LoadCharacterPreview()
    {
        // Can't spawn the character dummy until the entity manager is fully initialised
        // (its MetaQuery/entity store is only set up during EntityManager.Initialize).
        // The LobbyUIController reloads the preview whenever the LobbyState is entered,
        // so it's safe to defer if preferences arrive before we're ready.
        if (_entityManager is EntityManager { Initialized: false })
            return;

        if (_preferences.Preferences?.SelectedCharacter is not HumanoidCharacterProfile humanoid)
        {
            AgentPreview.ClearPreview();
            AgentNameLabel.Text = "UNKNOWN";
            return;
        }

        // The character preview can't spawn a humanoid for a species that lacks a doll
        // prototype, which would otherwise throw at runtime. Fall back to the default
        // species in that case so the lobby always has a working preview.
        if (!_proto.HasIndex<SpeciesPrototype>(humanoid.Species)
            || _proto.Index<SpeciesPrototype>(humanoid.Species).DollPrototype == default)
        {
            humanoid = new HumanoidCharacterProfile(humanoid)
            {
                Species = HumanoidCharacterProfile.DefaultSpecies,
            };
        }

        AgentPreview.LoadPreview(humanoid);
        AgentNameLabel.Text = humanoid.Name;

        if (AgentTitleLabel.FontOverride == null)
            AgentTitleLabel.FontOverride = _displayRegular;
        AgentNameLabel.FontOverride = _displayRegular;
    }

    public void UpdatePlayerProgression(int level, int odens, int bonds, int tier)
    {
        LevelValue.Text = level.ToString();
        OdensValue.Text = odens.ToString();
        BondsValue.Text = bonds.ToString();
        TierValue.Text = tier.ToString();
    }

    public void UpdateMatchStats(int readyCount, int activeCount, TimeSpan respawnRemaining, int cycle)
    {
        ReadyCountValue.Text = readyCount.ToString();
        ActiveCountValue.Text = activeCount.ToString();

        RespawnTimerValue.Text = respawnRemaining <= TimeSpan.Zero
            ? "0:00"
            : $"{(int) Math.Ceiling(respawnRemaining.TotalSeconds) / 60}:{(int) Math.Ceiling(respawnRemaining.TotalSeconds) % 60:00}";

        CycleValue.Text = cycle.ToString();
    }

    public void UpdateDiagnostics(float frameTime)
    {
        var ticker = _entityManager.System<ClientGameTicker>();
        if (ticker.AreWeReady != _areWeReady)
            SetReadyState(ticker.AreWeReady);

        UpdateNavAnimations(frameTime);
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);
    }
}
