using System;
using System.Collections.Generic;
using System.Numerics;
using Content.Client.GameTicking.Managers;
using Content.Client.Lobby;
using Content.Client.Lobby.UI;
using Content.Client.Lobby.UI.ProfileEditorControls;
using Content.Client.Resources;
using Content.Client.UserInterface.Systems.Chat.Widgets;
using Content.Shared.Preferences;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.IoC;
using Robust.Shared.Maths;
using SixLabors.ImageSharp.PixelFormats;

namespace Content.Client._Nivalis.UserInterface.Lobby;

/// <summary>
///     Custom apocalyptic / cyberpunk lobby overlay for Nivalis-232.
///     Long slim Orbitron nav buttons with a continuous light-blue scanline and
///     faint blue backing, a slight rightward slant, a 1.3x hover pop, a
///     full-height chat sidebar and a banked Quit button.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class NivalisLobbyControl : Control
{
    /// <summary>
    ///     Raised when a nav button needs the host lobby to act. Values: loadout,
    ///     challenges, quartermaster, settings.
    /// </summary>
    public event Action<string>? NavigationPressed;

    [Dependency] private readonly IClientPreferencesManager _preferences = default!;
    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly IClientConsoleHost _consoleHost = default!;
    [Dependency] private readonly IResourceCache _resourceCache = default!;
    [Dependency] private readonly IUriOpener _uriOpener = default!;

    private readonly Dictionary<Button, StyleBox> _navBase = new();
    private readonly Dictionary<Button, Vector2> _navBaseSize = new();
    private readonly Dictionary<Button, int> _navIndex = new();

    private bool _areWeReady;
    private Texture? _scanlineTexture;

    // Orbitron (bundled from the provided distribution).
    private Font _displayBold = null!;
    private Font _displayRegular = null!;

    public NivalisLobbyControl()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        _displayBold = _resourceCache.GetFont("/Fonts/Orbitron/Orbitron-Bold.ttf", 28);
        _displayRegular = _resourceCache.GetFont("/Fonts/Orbitron/Orbitron-Regular.ttf", 15);

        // Position anchored regions on the fullscreen LayoutContainer root.
        LayoutContainer.SetAnchorPreset(BackgroundViewport, LayoutContainer.LayoutPreset.Wide);
        LayoutContainer.SetAnchorAndMarginPreset(Header, LayoutContainer.LayoutPreset.TopWide, margin: 20);
        LayoutContainer.SetAnchorAndMarginPreset(ChatPanel, LayoutContainer.LayoutPreset.RightWide, margin: 18);
        LayoutContainer.SetAnchorAndMarginPreset(CharacterViewport, LayoutContainer.LayoutPreset.Center);
        LayoutContainer.SetAnchorAndMarginPreset(Navigation, LayoutContainer.LayoutPreset.CenterLeft, margin: 30);
        LayoutContainer.SetAnchorAndMarginPreset(ProgressionBox, LayoutContainer.LayoutPreset.BottomLeft, margin: 24);

        // Thin continuous light-blue scanline texture (fades on the right).
        _scanlineTexture = GenerateScanlines();

        // No backdrop gradient: the scanline chrome is applied directly to the
        // UI panels, and the full-screen sits on the vanilla background.
        BackgroundViewport.Texture = null;

        // Apply the Orbitron font to the header chrome.
        TitleLabel.FontOverride = _displayBold;
        TitleLabel.Margin = new Thickness(0, 0, 0, 4);
        foreach (var label in HeaderLabels())
            label.FontOverride = _displayRegular;

        // Wire the interactive menu buttons.
        ReadyButton.OnPressed += OnReadyPressed;
        LoadoutButton.OnPressed += _ => NavigationPressed?.Invoke("loadout");
        ChallengesButton.OnPressed += _ => NavigationPressed?.Invoke("challenges");
        QuartermasterButton.OnPressed += _ => NavigationPressed?.Invoke("quartermaster");
        PatreonButton.OnPressed += _ => _uriOpener.OpenUri("https://www.patreon.com/cw/lynnite");
        SettingsButton.OnPressed += _ => NavigationPressed?.Invoke("settings");
        QuitButton.OnPressed += _ => _consoleHost.ExecuteCommand("disconnect");

        SetupNavButtons();

        _preferences.OnServerDataLoaded += LoadCharacterPreview;
        LoadCharacterPreview();
    }

    private IEnumerable<Label> HeaderLabels()
    {
        yield return ReadyCountValue;
        yield return ActiveCountValue;
        yield return RespawnTimerValue;
        yield return CycleValue;
        yield return LevelValue;
        yield return OdensValue;
        yield return BondsValue;
        yield return TierValue;
    }

    /// <summary>
    ///     Moves the vanilla lobby chat into the full-height Nivalis right sidebar
    ///     and restyles it in a lighter, colder tone (OOC posts through as normal).
    /// </summary>
    public void AttachChat(ChatBox chat)
    {
        chat.Orphan();
        ChatSlot.AddChild(chat);
        chat.Margin = new Thickness(2, 2, 2, 2);
        chat.MinSize = default;
        chat.HorizontalExpand = true;
        chat.VerticalExpand = true;

        chat.ChatWindowPanel.MinSize = default;
        chat.ChatWindowPanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = Color.FromHex("#1a2a3acc"),
            BorderColor = Color.FromHex("#3a8fd8"),
            BorderThickness = new Thickness(1, 1, 1, 1),
        };
    }

    /// <summary>
    ///     Hides the standard SS14 lobby widgets (right panel, music credits).
    ///     Chat is moved into this overlay via <see cref="AttachChat"/>.
    /// </summary>
    public void HideDefaultLobby(LobbyGui lobby, ChatBox chat)
    {
        lobby.RightSide.Visible = false;
        AttachChat(chat);

        if (lobby.LobbySong.Parent is { } songParent)
            songParent.Visible = false;
    }

    /// <summary>
    ///     Thin, continuous light-blue scanlines that fade to the right. Each row
    ///     draws one unbroken line (used as button backing).
    /// </summary>
    private static Texture GenerateScanlines()
    {
        const int width = 256;
        const int height = 24;

        using var image = new SixLabors.ImageSharp.Image<Rgba32>(
            SixLabors.ImageSharp.Configuration.Default, width, height, new Rgba32(0x1b, 0x3a, 0x59, 0x99));

        for (var y = 0; y < height; y++)
        {
            var lit = (y % 6) == 1; // one continuous light line per group
            for (var x = 0; x < width; x++)
            {
                var tx = x / (float) (width - 1);
                var fade = 1f - tx * 1.1f;
                if (fade < 0f) fade = 0f;

                if (lit)
                    image[x, y] = new Rgba32(0x8f, 0xd8, 0xff, (byte) (235f * fade)); // light blue
            }
        }

        return Texture.LoadFromImage(image, "NivalisScanlines");
    }

    /// <summary>
    ///     Styles the long slim nav buttons with a continuous light-blue scanline
    ///     and faint blue backing, a rightward slant, and a lighter 1.3x hover pop.
    /// </summary>
    private void SetupNavButtons()
    {
        var buttons = new[] { ReadyButton, LoadoutButton, ChallengesButton, QuartermasterButton, PatreonButton, SettingsButton, QuitButton };
        for (var i = 0; i < buttons.Length; i++)
        {
            var button = buttons[i];
            // Rightward perspective slant: each successive button nudges right.
            button.Margin = new Thickness(i * 5, 0, 0, 4);
            button.HorizontalExpand = false;
            button.HorizontalAlignment = HAlignment.Left;
            _navIndex[button] = i;
            _navBaseSize[button] = new Vector2(button.MinWidth, button.MinHeight);

            var scanlineBox = new StyleBoxTexture
            {
                Texture = _scanlineTexture,
                PatchMarginLeft = 0,
                PatchMarginTop = 0,
                PatchMarginRight = 0,
                PatchMarginBottom = 0,
                Mode = StyleBoxTexture.StretchMode.Stretch,
            };

            _navBase[button] = scanlineBox;
            button.StyleBoxOverride = scanlineBox;

            button.OnMouseEntered += _ => OnNavHover(button, true);
            button.OnMouseExited += _ => OnNavHover(button, false);
        }
    }

    private void OnNavHover(Button button, bool hovering)
    {
        if (!_navBaseSize.TryGetValue(button, out var baseSize))
            return;

        var offset = _navIndex.GetValueOrDefault(button);
        if (hovering)
        {
            // Slightly lighter color scheme + 1.3x larger.
            var grown = new Vector2(baseSize.X * 1.3f, baseSize.Y * 1.3f);
            button.MinSize = grown;

            var scanlineBox = new StyleBoxTexture
            {
                Texture = _scanlineTexture,
                PatchMarginLeft = 0,
                PatchMarginTop = 0,
                PatchMarginRight = 0,
                PatchMarginBottom = 0,
                Mode = StyleBoxTexture.StretchMode.Stretch,
                Modulate = Color.FromHex("#CCFFFFFF"),
            };
            button.StyleBoxOverride = scanlineBox;
        }
        else
        {
            button.MinSize = new Vector2(baseSize.X, baseSize.Y);
            button.StyleBoxOverride = _navBase[button];
        }
    }

    /// <summary>
    ///     READY button: toggles the player's ready state via the standard
    ///     <c>toggleready</c> command and updates the label immediately.
    /// </summary>
    private void OnReadyPressed(BaseButton.ButtonEventArgs args)
    {
        var ticker = _entityManager.System<ClientGameTicker>();
        var newState = !ticker.AreWeReady;
        _consoleHost.ExecuteCommand($"toggleready {newState}");
        SetReadyState(newState);
    }

    /// <summary>
    ///     Updates the READY button text to match the current ready state.
    /// </summary>
    public void SetReadyState(bool ready)
    {
        _areWeReady = ready;
        ReadyButton.Text = ready ? "READY" : "NOT READY";
    }

    /// <summary>
    ///     Loads the player's selected character for the center dummy.
    /// </summary>
    public void LoadCharacterPreview()
    {
        if (_preferences.Preferences?.SelectedCharacter is not HumanoidCharacterProfile humanoid)
        {
            AgentPreview.ClearPreview();
            AgentNameLabel.Text = "UNKNOWN";
            return;
        }

        AgentPreview.LoadPreview(humanoid);
        AgentNameLabel.Text = humanoid.Name;

        if (AgentTitleLabel.FontOverride == null)
            AgentTitleLabel.FontOverride = _displayRegular;
        AgentNameLabel.FontOverride = _displayRegular;
    }

    /// <summary>
    ///     Updates the bottom-left stat stack (LEVEL / ODENS / BONDS / TIER).
    /// </summary>
    public void UpdatePlayerProgression(int level, int odens, int bonds, int tier)
    {
        LevelValue.Text = level.ToString();
        OdensValue.Text = odens.ToString();
        BondsValue.Text = bonds.ToString();
        TierValue.Text = tier.ToString();
    }

    /// <summary>
    ///     Syncs the top header metric row (AGENTS READY / ALIVE / RESPAWN IN / NIGHT).
    /// </summary>
    public void UpdateMatchStats(int readyCount, int activeCount, TimeSpan respawnRemaining, int cycle)
    {
        ReadyCountValue.Text = readyCount.ToString();
        ActiveCountValue.Text = activeCount.ToString();

        RespawnTimerValue.Text = respawnRemaining <= TimeSpan.Zero
            ? "0:00"
            : $"{(int) Math.Ceiling(respawnRemaining.TotalSeconds) / 60}:{(int) Math.Ceiling(respawnRemaining.TotalSeconds) % 60:00}";

        CycleValue.Text = cycle.ToString();
    }

    /// <summary>
    ///     Reconciles the READY button label with the authoritative ready state.
    /// </summary>
    public void UpdateDiagnostics(float frameTime)
    {
        var ticker = _entityManager.System<ClientGameTicker>();
        if (ticker.AreWeReady != _areWeReady)
            SetReadyState(ticker.AreWeReady);
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);
        if (disposing)
            _preferences.OnServerDataLoaded -= LoadCharacterPreview;
    }
}
