using Content.Shared._Nivalis.Traits;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Player;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client._Nivalis.UserInterface.Traits;

[GenerateTypedNameReferences]
public sealed partial class NivalisTraitsWidget : UIWidget
{
    [Dependency] private IEntityManager _entity = default!;
    [Dependency] private IPlayerManager _player = default!;
    [Dependency] private IPrototypeManager _proto = default!;

    private readonly List<string> _traitIds = new();

    public NivalisTraitsWidget()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        NivalisTraitComponent? traits = null;
        if (_player.LocalEntity is { } local)
            _entity.TryGetComponent(local, out traits);

        if (traits == null || traits.Traits.Count == 0)
        {
            Visible = false;
            return;
        }

        Visible = true;

        if (_traitIds.Count != traits.Traits.Count)
        {
            Rebuild(traits);
            return;
        }

        for (var i = 0; i < traits.Traits.Count; i++)
        {
            if (_traitIds[i] != traits.Traits[i].Id)
            {
                Rebuild(traits);
                return;
            }
        }
    }

    private void Rebuild(NivalisTraitComponent traits)
    {
        _traitIds.Clear();
        TraitContainer.RemoveAllChildren();

        foreach (var traitId in traits.Traits)
        {
            _traitIds.Add(traitId.Id);
            var name = _proto.TryIndex<NivalisTraitPrototype>(traitId.Id, out var trait)
                ? Loc.GetString(trait.Name)
                : traitId.Id;

            var chip = new Label
            {
                Text = name,
                StyleClasses = { "LabelSmall" },
                Margin = new Thickness(4, 1, 4, 1),
            };
            TraitContainer.AddChild(chip);
        }
    }
}
