using System;
using System.Collections.Generic;
using System.Numerics;
using Content.Client._Nivalis.UserInterface.Lobby;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;

namespace Content.Client._Nivalis.UserInterface.Hands;

[GenerateTypedNameReferences]
public sealed partial class NivalisHandsBar : UIWidget
{
    private const float ActiveScale = 1.08f;
    private const float HoverScale = 1.06f;
    private const float LerpSpeed = 9f;
    private const float IdleScrollSpeed = 9f;
    private const float HoverScrollSpeed = 26f;

    private readonly List<HandButtonState> _buttons = new();
    private Texture? _scanline;

    public NivalisHandsBar()
    {
        RobustXamlLoader.Load(this);
        _scanline = GenerateScanlines();
    }

    public void ClearHandButtons()
    {
        _buttons.Clear();
        HandButtonContainer.RemoveAllChildren();
    }

    public void AddHandButton(Button button, int index, bool active)
    {
        var style = new ScrollingScanlineStyleBox
        {
            Texture = _scanline,
            BackgroundColor = new Color(0.06f, 0.12f, 0.20f),
        };
        button.StyleBoxOverride = style;

        var baseSize = new Vector2(190, 20);
        button.MinSize = baseSize;
        button.Margin = new Thickness(index * 14, 0, 0, 3);
        button.HorizontalExpand = false;
        button.HorizontalAlignment = HAlignment.Left;

        var state = new HandButtonState
        {
            Button = button,
            Style = style,
            BaseSize = baseSize,
            CurrentSize = baseSize,
            TargetSize = baseSize,
            Active = active,
            Hover = false,
            HoverAmount = active ? 1f : 0f,
        };

        button.OnMouseEntered += _ => state.Hover = true;
        button.OnMouseExited += _ => state.Hover = false;

        _buttons.Add(state);
        HandButtonContainer.AddChild(button);
    }

    public void SetItems(List<string> itemNames)
    {
        for (var i = 0; i < _buttons.Count; i++)
        {
            var text = (i + 1).ToString();
            if (i < itemNames.Count && !string.IsNullOrWhiteSpace(itemNames[i]))
                text = $"{i + 1}  {itemNames[i]}";
            _buttons[i].Button.Text = text;
        }
    }

    public void SetActive(int index)
    {
        for (var i = 0; i < _buttons.Count; i++)
        {
            _buttons[i].Active = i == index;
        }
    }

    public void UpdateFrame(float frameTime)
    {
        foreach (var state in _buttons)
        {
            if (state.Active)
                state.TargetSize = new Vector2(state.BaseSize.X * ActiveScale, state.BaseSize.Y * ActiveScale);
            else if (state.Hover)
                state.TargetSize = new Vector2(state.BaseSize.X * HoverScale, state.BaseSize.Y * HoverScale);
            else
                state.TargetSize = state.BaseSize;

            var lerp = 1f - MathF.Exp(-LerpSpeed * frameTime);
            state.CurrentSize = new Vector2(
                state.CurrentSize.X + (state.TargetSize.X - state.CurrentSize.X) * lerp,
                state.CurrentSize.Y + (state.TargetSize.Y - state.CurrentSize.Y) * lerp);
            state.Button.MinSize = state.CurrentSize;

            var speed = state.Active || state.Hover ? HoverScrollSpeed : IdleScrollSpeed;
            state.Style.ScrollOffset += frameTime * speed;

            var bright = state.Active ? 1f : 0.82f + 0.14f * (state.Hover ? 1f : 0f);
            state.Style.Modulate = new Color(bright, bright, bright, 1f);
        }
    }

    private static Texture GenerateScanlines()
    {
        const int width = 64;
        const int height = 6;

        using var image = new SixLabors.ImageSharp.Image<SixLabors.ImageSharp.PixelFormats.Rgba32>(
            SixLabors.ImageSharp.Configuration.Default, width, height);
        for (var y = 0; y < height; y++)
        {
            var dark = (y == 1 || y == 3);
            byte r = 20, g = 40, b = 70, a = 0;
            if (dark)
            {
                a = 150;
                r = 30; g = 45; b = 90;
            }
            else if (y == 2)
            {
                a = 70;
                r = 160; g = 215; b = 255;
            }

            for (var x = 0; x < width; x++)
            {
                image[x, y] = new SixLabors.ImageSharp.PixelFormats.Rgba32(r, g, b, a);
            }
        }

        return Texture.LoadFromImage(image, "NivalisHandsScanlines");
    }

    private sealed class HandButtonState
    {
        public Button Button = null!;
        public ScrollingScanlineStyleBox Style = null!;
        public Vector2 BaseSize;
        public Vector2 CurrentSize;
        public Vector2 TargetSize;
        public bool Active;
        public bool Hover;
        public float HoverAmount;
    }
}
