using System;
using System.Collections.Generic;
using System.Numerics;
using Content.Client._Nivalis.UserInterface.Lobby;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;

namespace Content.Client._Nivalis.UserInterface.Hands;

[GenerateTypedNameReferences]
public sealed partial class NivalisHandsBar : UIWidget
{
    private static readonly Color BoxBackground = Color.FromHex("#4a82bf");
    private static readonly Color BoxBorder = Color.FromHex("#bfe3ff").WithAlpha(0.7f);
    private const float BoxBorderThickness = 1.5f;
    private const float BoxInwardLean = 0f;
    private const float BoxSlant = 10f;

    private const float ActiveBrightness = 1.0f;
    private const float IdleBrightness = 0.6f;
    private const float LerpSpeed = 10f;
    private const float IdleScrollSpeed = 9f;
    private const float ActiveScrollSpeed = 26f;

    private static readonly Vector2 BoxSize = new(190, 30);

    private readonly List<HandButtonState> _buttons = new();
    private Texture? _scanline;

    public NivalisHandsBar()
    {
        RobustXamlLoader.Load(this);
        _scanline = GenerateScanlines();
    }

    public void ClearHandButtons()
    {
        _buttons.Clear();
        HandButtonContainer.RemoveAllChildren();
    }

    public void AddHandButton(SlantedButton button, int index, bool active)
    {
        var style = new ScrollingScanlineStyleBox
        {
            Texture = _scanline,
            BackgroundColor = BoxBackground,
            BorderColor = BoxBorder,
            BorderThickness = BoxBorderThickness,
            InwardLean = BoxInwardLean,
            SlantPixels = BoxSlant,
        };
        button.StyleBoxOverride = style;

        button.MinSize = BoxSize;
        button.HorizontalExpand = false;
        button.HorizontalAlignment = HAlignment.Left;
        button.TextAlign = Label.AlignMode.Left;
        button.Shear = BoxSlant;
        button.Margin = new Thickness(BoxSlant, 0, 0, 0);

        var state = new HandButtonState
        {
            Button = button,
            Style = style,
            Active = active,
            Brightness = active ? ActiveBrightness : IdleBrightness,
            TargetBrightness = active ? ActiveBrightness : IdleBrightness,
        };

        _buttons.Add(state);
        HandButtonContainer.AddChild(button);
    }

    public void SetItems(IReadOnlyList<string?> itemNames)
    {
        for (var i = 0; i < _buttons.Count; i++)
        {
            var name = i < itemNames.Count ? itemNames[i] : null;
            _buttons[i].Button.Text = string.IsNullOrWhiteSpace(name) ? string.Empty : name;
        }
    }

    public void SetActive(int index)
    {
        for (var i = 0; i < _buttons.Count; i++)
        {
            var state = _buttons[i];
            state.Active = i == index;
            state.TargetBrightness = state.Active ? ActiveBrightness : IdleBrightness;
        }
    }

    public void UpdateFrame(float frameTime)
    {
        var lerp = 1f - MathF.Exp(-LerpSpeed * frameTime);

        foreach (var state in _buttons)
        {
            state.Brightness += (state.TargetBrightness - state.Brightness) * lerp;

            var bright = state.Brightness;
            state.Style.Modulate = new Color(bright, bright, bright, 1f);

            var speed = state.Active ? ActiveScrollSpeed : IdleScrollSpeed;
            state.Style.ScrollOffset += frameTime * speed;
        }
    }

    private static Texture GenerateScanlines()
    {
        const int width = 64;
        const int height = 6;

        using var image = new SixLabors.ImageSharp.Image<SixLabors.ImageSharp.PixelFormats.Rgba32>(
            SixLabors.ImageSharp.Configuration.Default, width, height);
        for (var y = 0; y < height; y++)
        {
            var dark = (y == 1 || y == 3);
            byte r = 20, g = 40, b = 70, a = 0;
            if (dark)
            {
                a = 150;
                r = 30; g = 45; b = 90;
            }
            else if (y == 2)
            {
                a = 70;
                r = 160; g = 215; b = 255;
            }

            for (var x = 0; x < width; x++)
            {
                image[x, y] = new SixLabors.ImageSharp.PixelFormats.Rgba32(r, g, b, a);
            }
        }

        return Texture.LoadFromImage(image, "NivalisHandsScanlines");
    }

    private sealed class HandButtonState
    {
        public SlantedButton Button = null!;
        public ScrollingScanlineStyleBox Style = null!;
        public bool Active;
        public float Brightness;
        public float TargetBrightness;
    }
}
