using System;
using Content.Shared._Nivalis.Perks;
using Content.Shared._Nivalis.Traits;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Nivalis.UserInterface.TraitDraft;

[GenerateTypedNameReferences]
public sealed partial class NivalisTraitDraftWindow : DefaultWindow
{
    public event Action<ProtoId<NivalisPerkPrototype>>? OnTraitPicked;

    public NivalisTraitDraftWindow()
    {
        RobustXamlLoader.Load(this);
        Title = Loc.GetString("nivalis-trait-draft-title");
    }

    public void Populate(List<NivalisTraitDraftChoice> choices)
    {
        DraftTitleLabel.Text = Loc.GetString("nivalis-trait-draft-prompt");
        ChoiceContainer.RemoveAllChildren();

        foreach (var choice in choices)
        {
            var box = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                Margin = new Thickness(4, 0, 4, 0),
                HorizontalExpand = true,
                VerticalExpand = true,
            };

            var button = new Button
            {
                Text = choice.Name ?? Loc.GetString("nivalis-trait-unnamed"),
                HorizontalExpand = true,
                StyleClasses = { "ButtonSquare" },
            };
            var picked = choice;
            button.OnPressed += _ => OnTraitPicked?.Invoke(picked.Id);
            box.AddChild(button);

            if (!string.IsNullOrEmpty(choice.Description))
            {
                box.AddChild(new RichTextLabel
                {
                    Text = choice.Description,
                    HorizontalExpand = true,
                    VerticalExpand = true,
                });
            }

            ChoiceContainer.AddChild(box);
        }
    }
}

