using Content.Client.Message;
using Content.Client.UserInterface.Systems.EscapeMenu;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Lobby.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class LobbyGui : UIScreen
    {
        [Dependency] private IClientConsoleHost _consoleHost = default!;

        public LobbyGui()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);
            SetAnchorPreset(MainContainer, LayoutPreset.Wide);
            SetAnchorPreset(Background, LayoutPreset.Wide);
            SetAnchorPreset(NivalisLobby, LayoutPreset.Wide);

            LobbySong.SetMarkup(Loc.GetString("lobby-state-song-no-song-text"));

            LeaveButton.OnPressed += _ => _consoleHost.ExecuteCommand("disconnect");
            OptionsButton.OnPressed += _ => UserInterfaceManager.GetUIController<OptionsUIController>().ToggleWindow();

            CollapseButton.OnPressed += _ => TogglePanel(false);
            ExpandButton.OnPressed += _ => TogglePanel(true);

            NivalisLobby.NavigationPressed += OnNivalisNavigation;
            NivalisLobby.Visible = true;
            Background.Visible = false;

            HideDefaultLobbyWidgets();
            NivalisLobby.HideDefaultLobby(this, Chat);
        }

        private void HideDefaultLobbyWidgets()
        {
            DefaultState.Visible = false;
            LeftSideTop.Visible = false;
            DevInfoBanner.Visible = false;
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
            if (disposing)
                NivalisLobby.NavigationPressed -= OnNivalisNavigation;
        }

        private void OnNivalisNavigation(string action)
        {
            switch (action)
            {
                case "loadout":
                    SwitchState(LobbyGuiState.CharacterSetup);
                    break;
                case "settings":
                    UserInterfaceManager.GetUIController<OptionsUIController>().ToggleWindow();
                    break;
                case "challenges":
                case "quartermaster": //nivalis todo add purpose for their life
                    break;
            }
        }

        public void SwitchState(LobbyGuiState state)
        {
            DefaultState.Visible = false;
            CharacterSetupState.Visible = false;

            switch (state)
            {
                case LobbyGuiState.Default:
                    DefaultState.Visible = false;
                    LeftSideTop.Visible = false;
                    DevInfoBanner.Visible = false;
                    RightSide.Visible = false;
                    NivalisLobby.Visible = true;
                    Background.Visible = false;
                    break;
                case LobbyGuiState.CharacterSetup:
                    CharacterSetupState.Visible = true;
                    NivalisLobby.Visible = false;
                    Background.Visible = true;

                    var actualWidth = (float) UserInterfaceManager.RootControl.PixelWidth;
                    var setupWidth = (float) LeftSide.PixelWidth;

                    if (1 - (setupWidth / actualWidth) > 0.30)
                    {
                        RightSide.Visible = false;
                    }

                    UserInterfaceManager.GetUIController<LobbyUIController>().ReloadCharacterSetup();

                    break;
            }
        }

        private void TogglePanel(bool value)
        {
            RightSide.Visible = value;
            ExpandPanel.Visible = !value;
        }

        public enum LobbyGuiState : byte
        {
            Default,
            CharacterSetup
        }
    }
}
