using Content.Client.Message;
using Content.Client.UserInterface.Systems.EscapeMenu;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using HumanoidCharacterProfile = Content.Shared.Preferences.HumanoidCharacterProfile;

namespace Content.Client.Lobby.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class LobbyGui : UIScreen
    {
        [Dependency] private IClientConsoleHost _consoleHost = default!;
        [Dependency] private IClientPreferencesManager _preferences = default!;

        public LobbyGui()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);
            SetAnchorPreset(MainContainer, LayoutPreset.Wide);
            SetAnchorPreset(Background, LayoutPreset.Wide);
            SetAnchorPreset(NivalisLobby, LayoutPreset.Wide);
            SetAnchorPreset(NivalisCustomization, LayoutPreset.Wide);

            LobbySong.SetMarkup(Loc.GetString("lobby-state-song-no-song-text"));

            LeaveButton.OnPressed += _ => _consoleHost.ExecuteCommand("disconnect");
            OptionsButton.OnPressed += _ => UserInterfaceManager.GetUIController<OptionsUIController>().ToggleWindow();

            CollapseButton.OnPressed += _ => TogglePanel(false);
            ExpandButton.OnPressed += _ => TogglePanel(true);

            NivalisLobby.NavigationPressed += OnNivalisNavigation;
            NivalisLobby.Visible = true;
            Background.Visible = false;

            NivalisCustomization.Closed += OnCustomizationClosed;
            NivalisCustomization.SetAnchorControl(NivalisLobby.LoadoutNavButton);

            HideDefaultLobbyWidgets();
            NivalisLobby.HideDefaultLobby(this, Chat);
        }

        private void OnCustomizationClosed()
        {
            NivalisCustomization.Visible = false;
            NivalisLobby.SetCustomizationOpen(false);
            UserInterfaceManager.GetUIController<LobbyUIController>().RefreshNivalisPreview();
        }

        private void ToggleCustomization()
        {
            if (NivalisCustomization.Visible)
            {
                NivalisCustomization.Visible = false;
                NivalisLobby.SetCustomizationOpen(false);
                return;
            }

            var profile = _preferences.Preferences?.SelectedCharacter as HumanoidCharacterProfile;
            NivalisCustomization.SetProfile(profile, _preferences.Preferences?.SelectedCharacterIndex);
            NivalisCustomization.Visible = true;
            NivalisLobby.SetCustomizationOpen(true);
        }

        private void HideDefaultLobbyWidgets()
        {
            DefaultState.Visible = false;
            LeftSideTop.Visible = false;
            DevInfoBanner.Visible = false;
        }

        protected override void ExitedTree()
        {
            base.ExitedTree();

            NivalisLobby.NavigationPressed -= OnNivalisNavigation;
            NivalisCustomization.Closed -= OnCustomizationClosed;
        }

        private void OnNivalisNavigation(string action)
        {
            switch (action)
            {
                case "loadout":
                    ToggleCustomization();
                    break;
                case "settings":
                    UserInterfaceManager.GetUIController<OptionsUIController>().ToggleWindow();
                    break;
                case "challenges":
                case "quartermaster": //nivalis todo add purpose for their life
                    break;
            }
        }

        public void SwitchState(LobbyGuiState state)
        {
            DefaultState.Visible = false;
            CharacterSetupState.Visible = false;

            switch (state)
            {
                case LobbyGuiState.Default:
                    DefaultState.Visible = false;
                    LeftSideTop.Visible = false;
                    DevInfoBanner.Visible = false;
                    RightSide.Visible = false;
                    NivalisLobby.Visible = true;
                    Background.Visible = false;
                    break;
                case LobbyGuiState.CharacterSetup:
                    CharacterSetupState.Visible = true;
                    NivalisLobby.Visible = false;
                    Background.Visible = true;

                    var actualWidth = (float)UserInterfaceManager.RootControl.PixelWidth;
                    var setupWidth = (float)LeftSide.PixelWidth;

                    if (1 - (setupWidth / actualWidth) > 0.30)
                    {
                        RightSide.Visible = false;
                    }

                    UserInterfaceManager.GetUIController<LobbyUIController>().ReloadCharacterSetup();

                    break;
            }
        }

        private void TogglePanel(bool value)
        {
            RightSide.Visible = value;
            ExpandPanel.Visible = !value;
        }

        public enum LobbyGuiState : byte
        {
            Default,
            CharacterSetup
        }
    }
}
