using Content.Shared._Nivalis.Perks;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Player;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client._Nivalis.UserInterface.Perks;

[GenerateTypedNameReferences]
public sealed partial class NivalisPerksWidget : UIWidget
{
    [Dependency] private IEntityManager _entity = default!;
    [Dependency] private IPlayerManager _player = default!;
    [Dependency] private IPrototypeManager _proto = default!;

    private readonly List<string> _perkIds = new();

    public NivalisPerksWidget()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        NivalisPerkComponent? perks = null;
        if (_player.LocalEntity is { } local)
            _entity.TryGetComponent(local, out perks);

        if (perks == null || perks.Perks.Count == 0)
        {
            Visible = false;
            return;
        }

        Visible = true;

        if (_perkIds.Count != perks.Perks.Count)
        {
            Rebuild(perks);
            return;
        }

        for (var i = 0; i < perks.Perks.Count; i++)
        {
            if (_perkIds[i] != perks.Perks[i].Id)
            {
                Rebuild(perks);
                return;
            }
        }
    }

    private void Rebuild(NivalisPerkComponent perks)
    {
        _perkIds.Clear();
        PerkContainer.RemoveAllChildren();

        foreach (var perkId in perks.Perks)
        {
            _perkIds.Add(perkId.Id);
            var name = _proto.TryIndex<NivalisPerkPrototype>(perkId.Id, out var perk)
                ? Loc.GetString(perk.Name)
                : perkId.Id;

            var chip = new Label
            {
                Text = name,
                StyleClasses = { "LabelSmall" },
                Margin = new Thickness(4, 1, 4, 1),
            };
            PerkContainer.AddChild(chip);
        }
    }
}
