using System.Collections.Generic;
using System.Numerics;
using Content.Client.Resources;
using Content.Client._Nivalis.UserInterface.Lobby;
using Content.Shared._Nivalis.Weapons;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Graphics;
using Robust.Shared.IoC;
using Robust.Shared.Maths;
using Robust.Shared.Timing;
using SixLabors.ImageSharp.PixelFormats;

namespace Content.Client._Nivalis.UserInterface.AmmoMenu;

[GenerateTypedNameReferences]
public sealed partial class NivalisAmmoMenuWindow : DefaultWindow
{
    private const float ScrollSpeed = 14f;

    [Dependency] private IResourceCache _resourceCache = default!;

    private readonly ScrollingScanlineStyleBox _scanline = new();
    private Texture? _scanlineTexture;

    private Action<NivalisAmmoType, int>? _dropAction;

    public NivalisAmmoMenuWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _scanlineTexture = GenerateScanlines();
        _scanline.Texture = _scanlineTexture;
        _scanline.BackgroundColor = new Color(13, 17, 25, 255);
        _scanline.Modulate = Color.White;

        if (ChildCount > 0 && Children[0] is PanelContainer windowPanel)
            windowPanel.PanelOverride = _scanline;

        WindowHeader.PanelOverride = _scanline;

        TitleLabel.Text = string.Empty;
        MainPanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = new Color(6, 9, 14, 235),
        };

        CloseAmmoButton.OnPressed += _ => Close();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        _scanline.ScrollOffset += args.DeltaSeconds * ScrollSpeed;
    }

    private static Texture GenerateScanlines()
    {
        const int width = 64;
        const int height = 6;

        using var image = new SixLabors.ImageSharp.Image<Rgba32>(
            SixLabors.ImageSharp.Configuration.Default, width, height);
        for (var y = 0; y < height; y++)
        {
            var dark = (y == 1 || y == 3);
            byte r = 20, g = 40, b = 70, a = 0;
            if (dark)
            {
                a = 150;
                r = 30; g = 45; b = 90;
            }
            else if (y == 2)
            {
                a = 70;
                r = 160; g = 215; b = 255;
            }

            for (var x = 0; x < width; x++)
            {
                image[x, y] = new Rgba32(r, g, b, a);
            }
        }

        return Texture.LoadFromImage(image, "NivalisAmmoSscanlines");
    }

    public void Populate(List<NivalisAmmoMenuEntry> entries)
    {
        AmmoList.RemoveAllChildren();

        foreach (var entry in entries)
        {
            var row = new PanelContainer
            {
                Margin = new Thickness(0, 0, 0, 0),
            };
            row.PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = entry.Count > 0 ? new Color(24, 36, 48, 200) : new Color(32, 24, 24, 200),
                BorderColor = entry.Count > 0 ? new Color(88, 198, 232, 120) : new Color(120, 70, 70, 120),
                BorderThickness = new Thickness(1, 1),
                Padding = new Thickness(4, 2, 4, 2),
            };

            var rowBox = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                SeparationOverride = 8,
            };
            row.AddChild(rowBox);

            var icon = new TextureRect
            {
                Texture = _resourceCache.GetTexture(entry.IconPath),
                TextureScale = new Vector2(2, 2),
                VerticalAlignment = VAlignment.Center,
            };
            rowBox.AddChild(icon);

            var name = new Label
            {
                Text = entry.Name,
                VerticalAlignment = VAlignment.Center,
                MinWidth = 120,
                FontColorOverride = new Color(0xE6, 0xE6, 0xE6),
            };
            rowBox.AddChild(name);

            var count = new Label
            {
                Text = Loc.GetString("nivalis-ammo-count", ("count", entry.Count)),
                FontColorOverride = entry.Count > 0 ? Color.FromHex("#d7df60") : Color.FromHex("#8FA3B8"),
                VerticalAlignment = VAlignment.Center,
                HorizontalAlignment = HAlignment.Right,
                HorizontalExpand = true,
            };
            rowBox.AddChild(count);

            // Drop this ammo type (all of it, or a fixed 6-round bundle) as a box.
            var type = entry.Type;
            var drop6 = new Button
            {
                Text = "6",
                MinWidth = 28,
                MinHeight = 24,
                Disabled = entry.Count <= 0,
            };
            drop6.OnPressed += _ => _dropAction?.Invoke(type, 6);
            rowBox.AddChild(drop6);

            var dropAll = new Button
            {
                Text = "ALL",
                MinWidth = 40,
                MinHeight = 24,
                Disabled = entry.Count <= 0,
            };
            dropAll.OnPressed += _ => _dropAction?.Invoke(type, entry.Count);
            rowBox.AddChild(dropAll);

            AmmoList.AddChild(row);
        }
    }

    public void SetDropAction(Action<NivalisAmmoType, int> dropAction)
    {
        _dropAction = dropAction;
    }
}

