using Content.Shared._Nivalis.Perks;
using Content.Shared.Ghost.Components;
using Content.Shared._Nivalis.GameTicking;
using Content.Shared._Nivalis.GameTicking.Components;
using Content.Shared._Nivalis.Status;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Localization;
using Robust.Shared.Player;
using Robust.Shared.Timing;
namespace Content.Client._Nivalis.UserInterface.SurvivalHud;

[GenerateTypedNameReferences]
public sealed partial class NivalisSurvivalHud : UIWidget
{
    [Dependency] private IEntityManager _entity = default!;
    [Dependency] private IPlayerManager _player = default!;
    [Dependency] private IGameTiming _timing = default!;
    [Dependency] private ILocalizationManager _loc = default!;
    [Dependency] private IEntityNetworkManager _net = default!;

    public NivalisSurvivalHud()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        ReturnToLobbyButton.OnPressed += _ => _net.SendSystemNetworkMessage(new NivalisReturnToLobbyMessage());
        PrevSurvivorButton.OnPressed += _ => _net.SendSystemNetworkMessage(new NivalisSpectateCycleMessage(false));
        NextSurvivorButton.OnPressed += _ => _net.SendSystemNetworkMessage(new NivalisSpectateCycleMessage(true));
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        var local = _player.LocalEntity;
        if (local == null || !_entity.EntityExists(local.Value))
        {
            Visible = false;
            return;
        }

        var localUid = local.Value;

        if (_entity.HasComponent<NivalisSurvivalResourceComponent>(localUid))
        {
            Visible = true;
            SurvivorBox.Visible = true;
            ReturnToLobbyButton.Visible = false;
            SpectatorControlsBox.Visible = false;

            var component = _entity.GetComponent<NivalisSurvivalResourceComponent>(localUid);
            HungerBar.MaxValue = component.MaxHunger;
            HungerBar.Value = component.Hunger;
            ThirstBar.MaxValue = component.MaxThirst;
            ThirstBar.Value = component.Thirst;

            UpdateStormHud();
            UpdateExecutionerHud(localUid);
            return;
        }

        if (_entity.HasComponent<GhostComponent>(localUid))
        {
            Visible = true;
            SurvivorBox.Visible = false;
            ReturnToLobbyButton.Visible = true;
            SpectatorControlsBox.Visible = true;

            NivalisSurvivalCycleComponent? cycle = null;
            foreach (var (_, comp) in _entity.EntityQueryEnumerator<NivalisSurvivalCycleComponent>())
            {
                cycle = comp;
                break;
            }

            PhaseLabel.Text = cycle?.Phase == NivalisSurvivalPhase.Storm
                ? _loc.GetString("nivalis-hud-phase-storm")
                : _loc.GetString("nivalis-hud-phase-scavenge");
            TimerLabel.Text = "";
            return;
        }

        Visible = false;
    }

    private void UpdateStormHud()
    {
        NivalisSurvivalCycleComponent? cycle = null;
        foreach (var (_, comp) in _entity.EntityQueryEnumerator<NivalisSurvivalCycleComponent>())
        {
            cycle = comp;
            break;
        }

        if (cycle == null)
        {
            PhaseLabel.Text = "---";
            TimerLabel.Text = "";
            return;
        }

        PhaseLabel.Text = cycle.Phase switch
        {
            NivalisSurvivalPhase.Storm => _loc.GetString("nivalis-hud-phase-storm"),
            _ => _loc.GetString("nivalis-hud-phase-scavenge"),
        };

        var remaining = cycle.PhaseEndTime - _timing.CurTime;
        if (remaining > TimeSpan.Zero)
            TimerLabel.Text = FormatCountdown(remaining);
        else
            TimerLabel.Text = "";
    }

    private static string FormatCountdown(TimeSpan time)
    {
        var totalSeconds = (int)Math.Ceiling(time.TotalSeconds);
        var minutes = totalSeconds / 60;
        var seconds = totalSeconds % 60;
        return $"{minutes:00}:{seconds:00}";
    }

    private void UpdateExecutionerHud(EntityUid localUid)
    {
        if (!_entity.TryGetComponent<NivalisPerkComponent>(localUid, out var perk) ||
            perk.Perk?.Id != "Executioner")
        {
            ExecutionerBox.Visible = false;
            return;
        }

        ExecutionerBox.Visible = true;

        var durability = 100f;
        var bounty = 0;
        var broken = false;
        var live = false;

        if (_entity.TryGetComponent<NivalisExecutionerComponent>(localUid, out var exec))
        {
            durability = exec.Durability;
            bounty = exec.BountyCount;
            broken = exec.Broken;
            live = exec.Live;
        }

        ExecutionerRemoveLabel.Visible = broken && live;

        NvgChargeBar.MaxValue = 100f;
        NvgChargeBar.Value = Math.Clamp(durability, 0f, 100f);
        NvgPctLabel.Text = $"{(int)MathF.Round(durability)}%";

        BountyLabel.Text = $"{bounty}x";
    }
}

