using Content.Shared._Nivalis.GameTicking.Components;
using Content.Shared._Nivalis.Status;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Localization;
using Robust.Shared.Player;
using Robust.Shared.Timing;

namespace Content.Client._Nivalis.UserInterface.SurvivalHud;

[GenerateTypedNameReferences]
public sealed partial class NivalisSurvivalHud : UIWidget
{
    [Dependency] private IEntityManager _entity = default!;
    [Dependency] private IPlayerManager _player = default!;
    [Dependency] private IGameTiming _timing = default!;
    [Dependency] private ILocalizationManager _loc = default!;

    public NivalisSurvivalHud()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        NivalisSurvivalResourceComponent? component = null;
        if (_player.LocalEntity is { } local)
            _entity.TryGetComponent(local, out component);

        if (component == null)
        {
            Visible = false;
            return;
        }

        Visible = true;
        HungerBar.MaxValue = component.MaxHunger;
        HungerBar.Value = component.Hunger;
        ThirstBar.MaxValue = component.MaxThirst;
        ThirstBar.Value = component.Thirst;

        UpdateStormHud();
    }

    private void UpdateStormHud()
    {
        NivalisSurvivalCycleComponent? cycle = null;
        foreach (var (_, comp) in _entity.EntityQueryEnumerator<NivalisSurvivalCycleComponent>())
        {
            cycle = comp;
            break;
        }

        if (cycle == null)
        {
            PhaseLabel.Text = "---";
            TimerLabel.Text = "";
            return;
        }

        PhaseLabel.Text = cycle.Phase switch
        {
            NivalisSurvivalPhase.Storm => _loc.GetString("nivalis-hud-phase-storm"),
            _ => _loc.GetString("nivalis-hud-phase-scavenge"),
        };

        var remaining = cycle.PhaseEndTime - _timing.CurTime;
        if (remaining > TimeSpan.Zero)
            TimerLabel.Text = FormatCountdown(remaining);
        else
            TimerLabel.Text = "";
    }

    private static string FormatCountdown(TimeSpan time)
    {
        var totalSeconds = (int) Math.Ceiling(time.TotalSeconds);
        var minutes = totalSeconds / 60;
        var seconds = totalSeconds % 60;
        return $"{minutes:00}:{seconds:00}";
    }
}
