using Content.Shared._Nivalis.Status;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Player;
using Robust.Shared.Timing;

namespace Content.Client._Nivalis.UserInterface.SurvivalHud;

[GenerateTypedNameReferences]
public sealed partial class NivalisSurvivalHud : UIWidget
{
    [Dependency] private readonly IEntityManager _entity = default!;
    [Dependency] private readonly IPlayerManager _player = default!;

    public NivalisSurvivalHud()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        NivalisSurvivalResourceComponent? component = null;
        if (_player.LocalEntity is { } local)
            _entity.TryGetComponent(local, out component);

        if (component == null)
        {
            Visible = false;
            return;
        }

        Visible = true;
        HungerBar.MaxValue = component.MaxHunger;
        HungerBar.Value = component.Hunger;
        ThirstBar.MaxValue = component.MaxThirst;
        ThirstBar.Value = component.Thirst;
    }
}

